# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

query = f"""
TRUNCATE TABLE {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_CREDITS;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------


query = f"""
INSERT INTO {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_CREDITS
(
	ORDER_ID,
	LINE,
	SUBLINE,
	CREDIT_NAME,
	RULE_TYPE,
	DESCRIPTION,
	BUSINESS_UNIT,
	COMPENSATION_DATE,
	PERIOD,
	CREDIT_GENERATED_DATE,
	EVENT_TYPE,
	PARTNER_CODE,
	CREDIT_OUTPUT_NAME,
	CREDIT_TYPE,
	CREDIT_AMOUNT,
	DISPLAY_NAME_FOR_REPORTS,
	GA1_EVENT_DESCRIPTION,
	GA2_DATA_SOURCE,
	GA3_DISCONNECTION_REASON,
	GA9_COMMITMENT_TYPE,
	GN1_COHORT_ID,
	GN2_PAYG_REV_SHARE_RATE,
	GN3_CONTRACT_DURATION,
	GN4_CONTRACT_ACTIVE_DURATION_IN_MONTHS,
	GN5_PRIOR_PAYMENT_PAID,
	GN6_PAID_FOR_CONTRACT_DURATION,
	GD6_DISCONNECTION_DATE,
	INSERT_TS,
	UPDATE_TS
)
SELECT
	SRC.ORDER_ID,
	SRC.LINE,
	SRC.SUBLINE,
	SRC.CREDIT_NAME,
	SRC.RULE_TYPE,
	SRC.DESCRIPTION,
	SRC.BUSINESS_UNIT,
	SRC.COMPENSATION_DATE,
	SRC.PERIOD,
	SRC.CREDIT_GENERATED_DATE,
	SRC.EVENT_TYPE,
	SRC.PARTNER_CODE,
	SRC.CREDIT_OUTPUT_NAME,
	SRC.CREDIT_TYPE,
	SRC.CREDIT_AMOUNT,
	SRC.DISPLAY_NAME_FOR_REPORTS,
	SRC.GA1_EVENT_DESCRIPTION,
	SRC.GA2_DATA_SOURCE,
	SRC.GA3_DISCONNECTION_REASON,
	SRC.GA9_COMMITMENT_TYPE,
	SRC.GN1_COHORT_ID,
	SRC.GN2_PAYG_REV_SHARE_RATE,
	SRC.GN3_CONTRACT_DURATION,
	SRC.GN4_CONTRACT_ACTIVE_DURATION_IN_MONTHS,
	SRC.GN5_PRIOR_PAYMENT_PAID,
	SRC.GN6_PAID_FOR_CONTRACT_DURATION,
	SRC.GD6_DISCONNECTION_DATE,
	SRC.INSERT_TS,
	SRC.UPDATE_TS
FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_CREDITS_STG SRC
WHERE SRC.INSERT_TS = (
	SELECT MAX(INSERT_TS)
	FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_CREDITS_STG
)
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)