# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

print(sfDatabase)

# COMMAND ----------

query = f"""
TRUNCATE TABLE {sfDatabase}.ATO_CEG_STG.CS_GENERICCLASSIFIER;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------


query = f"""
INSERT INTO {sfDatabase}.ATO_CEG_STG.CS_GENERICCLASSIFIER
(
	TENANTID,
	CLASSIFIERSEQ,
	EFFECTIVESTARTDATE,
	EFFECTIVEENDDATE,
	ISLAST,
	CREATEDATE,
	REMOVEDATE,
	GENERICATTRIBUTE1,
	GENERICATTRIBUTE2,
	GENERICATTRIBUTE3,
	GENERICATTRIBUTE4,
	GENERICATTRIBUTE5,
	GENERICATTRIBUTE6,
	GENERICATTRIBUTE7,
	GENERICATTRIBUTE8,
	GENERICATTRIBUTE9,
	GENERICATTRIBUTE10,
	GENERICATTRIBUTE11,
	GENERICATTRIBUTE12,
	GENERICATTRIBUTE13,
	GENERICATTRIBUTE14,
	GENERICATTRIBUTE15,
	GENERICATTRIBUTE16,
	GENERICNUMBER1,
	GENERICNUMBER2,
	GENERICNUMBER3,
	GENERICNUMBER4,
	GENERICNUMBER5,
	GENERICNUMBER6,
	UNITTYPEFORGENERICNUMBER1,
	UNITTYPEFORGENERICNUMBER2,
	UNITTYPEFORGENERICNUMBER3,
	UNITTYPEFORGENERICNUMBER4,
	UNITTYPEFORGENERICNUMBER5,
	UNITTYPEFORGENERICNUMBER6,
	GENERICDATE1,
	GENERICDATE2,
	GENERICDATE3,
	GENERICDATE4,
	GENERICDATE5,
	GENERICDATE6,
	GENERICBOOLEAN1,
	GENERICBOOLEAN2,
	GENERICBOOLEAN3,
	GENERICBOOLEAN4,
	GENERICBOOLEAN5,
	GENERICBOOLEAN6,
	INSERT_TS,
	UPDATE_TS
)
SELECT
	SRC.TENANTID,
	SRC.CLASSIFIERSEQ,
	SRC.EFFECTIVESTARTDATE,
	SRC.EFFECTIVEENDDATE,
	SRC.ISLAST,
	SRC.CREATEDATE,
	SRC.REMOVEDATE,
	SRC.GENERICATTRIBUTE1,
	SRC.GENERICATTRIBUTE2,
	SRC.GENERICATTRIBUTE3,
	SRC.GENERICATTRIBUTE4,
	SRC.GENERICATTRIBUTE5,
	SRC.GENERICATTRIBUTE6,
	SRC.GENERICATTRIBUTE7,
	SRC.GENERICATTRIBUTE8,
	SRC.GENERICATTRIBUTE9,
	SRC.GENERICATTRIBUTE10,
	SRC.GENERICATTRIBUTE11,
	SRC.GENERICATTRIBUTE12,
	SRC.GENERICATTRIBUTE13,
	SRC.GENERICATTRIBUTE14,
	SRC.GENERICATTRIBUTE15,
	SRC.GENERICATTRIBUTE16,
	SRC.GENERICNUMBER1,
	SRC.GENERICNUMBER2,
	SRC.GENERICNUMBER3,
	SRC.GENERICNUMBER4,
	SRC.GENERICNUMBER5,
	SRC.GENERICNUMBER6,
	SRC.UNITTYPEFORGENERICNUMBER1,
	SRC.UNITTYPEFORGENERICNUMBER2,
	SRC.UNITTYPEFORGENERICNUMBER3,
	SRC.UNITTYPEFORGENERICNUMBER4,
	SRC.UNITTYPEFORGENERICNUMBER5,
	SRC.UNITTYPEFORGENERICNUMBER6,
	SRC.GENERICDATE1,
	SRC.GENERICDATE2,
	SRC.GENERICDATE3,
	SRC.GENERICDATE4,
	SRC.GENERICDATE5,
	SRC.GENERICDATE6,
	SRC.GENERICBOOLEAN1,
	SRC.GENERICBOOLEAN2,
	SRC.GENERICBOOLEAN3,
	SRC.GENERICBOOLEAN4,
	SRC.GENERICBOOLEAN5,
	SRC.GENERICBOOLEAN6,
	SRC.INSERT_TS,
	SRC.UPDATE_TS
FROM {sfDatabase}.ATO_CEG_STG.CS_GENERICCLASSIFIER_STG SRC
WHERE SRC.INSERT_TS = (
	SELECT MAX(INSERT_TS)
	FROM {sfDatabase}.ATO_CEG_STG.CS_GENERICCLASSIFIER_STG
)
;


"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)