# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

period_name_value = dbutils.widgets.get("PERIOD_NAME")
# period_name_value = 'April 2026 M'
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.PAYG_ITU_REBATE
--WHERE PERIODNAME = INITCAP(TRIM(TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'MMMM')))
--           || ' ' ||
--           TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'YYYY')
--           || ' M'
WHERE PERIODNAME = '{period_name_value}'
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

CREATE OR REPLACE TEMP TABLE {sfDatabase}.ATO_CEG_STG.PAYG_ITU_REBATE_TEMP AS
SELECT
    CRED.PERIOD                       AS PERIODNAME,
    MAX(SALESTRANS.LINE_NUMBER)       AS LINENUMBER,
    MAX(SALESTRANS.SUBLINE_NUMBER)    AS SUBLINENUMBER,
    MAX(SALESTRANS.EVENT_TYPE_ID)     AS EVENTTYPEID,
    SALESTRANS.COMPENSATION_DATE      AS COMPENSATIONDATE,
    SALESTRANS.ORDER_ID               AS ORDERID,
    --SALESTRANS.GENERIC_ATTRIBUTE_10   AS ORACLE_ORDER_ID, --commented
    SALESTRANS.ALTERNATE_ORDER_NUMBER   AS ORACLE_ORDER_ID, ---changed
    SALESTRANS.GENERIC_ATTRIBUTE_20   AS PARTNER_CODE,
    --SALESTRANS.GENERIC_ATTRIBUTE_22   AS PARTNER_NAME, --commented
    SALESTRANS.GENERIC_ATTRIBUTE_21   AS PARTNER_NAME,   ---changed
    SALESTRANS.GENERIC_ATTRIBUTE_1    AS PRODUCT_CODE,
    SALESTRANS.GENERIC_ATTRIBUTE_2    AS PRODUCT_DESC,
    --SALESTRANS.GENERIC_NUMBER_1       AS RRP_EX_VAT, --commented
    SALESTRANS.UNIT_VALUE       AS RRP_EX_VAT,         ---changed
    --SUM(SALESTRANS.GENERIC_NUMBER_4)  AS SHIPMENT_QTY, --commented
    SUM(SALESTRANS.NUMBER_OF_UNITS)  AS SHIPMENT_QTY,    ---changed
    MAX(CRED.CREDIT_OUTPUT_NAME)      AS CREDIT_NAME,
	
	
    CASE WHEN UPPER(TRIM(CRED.CREDIT_OUTPUT_NAME)) = 'CR_MCAL_IP_PAYG_ITU_REBATE' AND NVL(CRED.CREDIT_AMOUNT, 0) <> 0 THEN 'N' 
	WHEN UPPER(TRIM(CRED.CREDIT_OUTPUT_NAME)) = 'CR_MCAL_IP_PAYG_ITU_ENHANCED_REBATE' AND NVL(CRED.CREDIT_AMOUNT, 0) <> 0 THEN 'Y'
    ELSE NULL END                     AS ENHANCED_REBATE_FLAG,
		
		
    CRED.CREDIT_AMOUNT                AS REBATE_RATE,
	--SUM(SALESTRANS.GENERIC_NUMBER_1)  AS GROSS_RRP_INVOICE_VALUE, --commented
    SUM(SALESTRANS.UNIT_VALUE)  AS GROSS_RRP_INVOICE_VALUE,         ---changed
    SUM(CRED.CREDIT_AMOUNT)           AS REBATE_VALUE
	
FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_CREDITS CRED
LEFT JOIN {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_SALES_ACTIVITY SALESTRANS
    ON  CRED.ORDER_ID   = SALESTRANS.ORDER_ID
    AND CRED.LINE       = SALESTRANS.LINE_NUMBER
    AND CRED.SUBLINE    = SALESTRANS.SUBLINE_NUMBER
    AND CRED.EVENT_TYPE = SALESTRANS.EVENT_TYPE_ID
    AND CRED.PERIOD     = SALESTRANS.PERIOD
    WHERE UPPER(TRIM(CRED.CREDIT_OUTPUT_NAME)) IN ( 'CR_MCAL_IP_PAYG_ITU_REBATE', 'CR_MCAL_IP_PAYG_ITU_ENHANCED_REBATE' )
	--AND CRED.PERIOD = INITCAP(TRIM(TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'MMMM')))
    --       || ' ' ||
    --       TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'YYYY')
    --       || ' M'
	AND CRED.PERIOD = '{period_name_value}'
	
GROUP BY
    SALESTRANS.ORDER_ID,
    --SALESTRANS.GENERIC_ATTRIBUTE_10, --commented
    SALESTRANS.ALTERNATE_ORDER_NUMBER, ---changed
    --SALESTRANS.GENERIC_ATTRIBUTE_22,  --commented
    SALESTRANS.GENERIC_ATTRIBUTE_21,    ---changed
    SALESTRANS.GENERIC_ATTRIBUTE_20,
    SALESTRANS.COMPENSATION_DATE,
    SALESTRANS.GENERIC_ATTRIBUTE_2,
	
    CASE WHEN UPPER(TRIM(CRED.CREDIT_OUTPUT_NAME)) = 'CR_MCAL_IP_PAYG_ITU_REBATE' AND NVL(CRED.CREDIT_AMOUNT, 0) <> 0 THEN 'N' 
	WHEN UPPER(TRIM(CRED.CREDIT_OUTPUT_NAME)) = 'CR_MCAL_IP_PAYG_ITU_ENHANCED_REBATE' AND NVL(CRED.CREDIT_AMOUNT, 0) <> 0 THEN 'Y'
    ELSE NULL END,
	
    --SALESTRANS.GENERIC_NUMBER_1, --commented
    SALESTRANS.UNIT_VALUE,         ---changed
    CRED.CREDIT_AMOUNT,
    SALESTRANS.GENERIC_ATTRIBUTE_1,
    CRED.PERIOD;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.PAYG_ITU_REBATE (
    PERIODNAME,
    LINENUMBER,
    SUBLINENUMBER,
    EVENTTYPEID,
    COMPENSATIONDATE,
    ORDERID,
    ORACLE_ORDER_ID,
    PARTNER_CODE,
    PARTNER_NAME,
    PRODUCT_CODE,
    PRODUCT_DESC,
    RRP_EX_VAT,
    SHIPMENT_QTY,
    CREDIT_NAME,
    ENHANCED_REBATE_FLAG,
    REBATE_RATE,
    MODIFIED_DATE,
	GROSS_RRP_INVOICE_VALUE,
	REBATE_VALUE,
    EXTRACT_RUN_DATE
	)
SELECT
    PERIODNAME,
    LINENUMBER,
    SUBLINENUMBER,
    EVENTTYPEID,
    COMPENSATIONDATE,
    ORDERID,
    ORACLE_ORDER_ID,
    PARTNER_CODE,
    PARTNER_NAME,
    PRODUCT_CODE,
    PRODUCT_DESC,
    RRP_EX_VAT,
    SHIPMENT_QTY,
    CREDIT_NAME,
    ENHANCED_REBATE_FLAG,
    REBATE_RATE,
    CURRENT_TIMESTAMP()  AS MODIFIED_DATE,
	GROSS_RRP_INVOICE_VALUE,
	REBATE_VALUE,
    CURRENT_TIMESTAMP
    
FROM {sfDatabase}.ATO_CEG_STG.PAYG_ITU_REBATE_TEMP
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()