# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

period_name_value = dbutils.widgets.get("PERIOD_NAME")
print(period_name_value)

# COMMAND ----------

query_crd = f"""
CREATE OR REPLACE TABLE SIT_IDW.ATO_ADX_STG.CRD AS
SELECT * 
FROM SIT_IDW.ATO_CEG_STG.tbl_fact_paym_credits

UNION ALL

SELECT * 
FROM SIT_IDW.ATO_CEG_STG.tbl_fact_payg_credits
"""

cs.execute(query_crd)

# COMMAND ----------

# %sql
# select count(*) from CRD;

# COMMAND ----------

query_otd = f"""
CREATE OR REPLACE TABLE SIT_IDW.ATO_ADX_STG.ORDER_TRANSACTION_DETAILS AS
SELECT * 
FROM SIT_IDW.ATO_CEG_STG.tbl_fact_paym_sales_activity
WHERE PERIOD = '{period_name_value}'

UNION ALL

SELECT * 
FROM SIT_IDW.ATO_CEG_STG.tbl_fact_payg_sales_activity
WHERE PERIOD = '{period_name_value}'
"""

cs.execute(query_otd)

# COMMAND ----------

# %sql
# select * from ORDER_TRANSACTION_DETAILS limit 10;

# COMMAND ----------

# %sql
# select count(*) from ORDER_TRANSACTION_DETAILS;

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_DETAILS
WHERE PERIOD_NAME = '{period_name_value}'
;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO SIT_IDW.PRS_CEG_EXT.B2C_DEALER_DETAILS
(
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    CONNECTION_ID,
    CONNECTION_DT,
    DISCONNECTION_DT,
    REASON_CODE,
    ADJUSTMENT_DATE,
    ADDON_DATE,
    IMEI1,
    IMEI2,
    EVENT_TYPE,
    INITAL_MSISDN,
    PORTIN_MSISDN,
    PLAN_DESCRIPTION,
    DEVICE_DESCRITPION,
    ICCID,
    PRODUCT_CODE,
    PRODUCT_DESC,
    TARIFF_CODE,
    TARIFF_DESC,
    SOURCE,
    ADDON_NAME,
    FIRST_NAME,
    LAST_NAME,
    SOLD_BY_DEALER_CODE,
    PARTNER_CODE,
    PARTNER_NAME,
    CREDIT_TYPE,
    CREDIT_NAME,
    COMPENSATION_DATE,
    ORDER_ID,
    LINE_NUMBER,
    COMMITMENT_TYPE,
    BUS_SERVICE_TYPE,
    CHANNEL,
    CONTRACT_TYPE,
    ADHOC_TRANS,
    TENURE,
    CREDIT_VAL,
    TRX_VAL,
    MODIFIED_DATE,
    SUBLINE_NUMBER,
    CONNECTIONS,
    LOB,
    WEEK_IN_YEAR,
    TRIPLE_NET,
    IND_REP_TARIFF,
    IND_REP_TARIFF_PRICE,
    IND_REP_ADDON_VALUE,
    IND_REP_DISCOUNT_VALUE,
    IND_REP_MRC,
    MRC_LESS_VAT,
    CUSTOMER_TYPE,
    COMMENTS,
    BUSINESS_TYPE,
    SERVICE_TYPE,
    PAYG_TOPUP_DT,
    TXN_REF_NO,
    ACCOUNTING_DATE,
    BAN,
    PRODUCT_GROUP,
    CHANNEL_FULL_NAME,
    CUSTOMER_STATUS,
    TARGETED_MRC,
    PARTNER_MARGIN,
    DEVICE_COST_PRICE
)


SELECT
    CRED.PERIOD AS PERIOD_NAME,
    PER.STARTDATE AS PERIOD_START_DATE,
    DATEADD(DAY, -1, PER.ENDDATE) AS PERIOD_END_DATE,
    CRED.ORDER_ID || '/' || CRED.LINE AS CONNECTION_ID,
    CASE
        WHEN TRIM(UPPER(CRED.CREDIT_TYPE)) NOT IN (
                'CT_ADVANCE_BACK_ADJ','CT_ADVANCE_ADJ','CT_MANUAL_ADJ',
                'CT_MANUAL_ADJ_MBB','CT_MANUAL_ADJ_HBB','CT_MANUAL_PAYMENT',
                'CT_VOLUME_ADJ','CT_VOLUME_ADJ_BP','CT_VOLUME_ADJ_BP_MBB','CT_VOLUME_ADJ_BP_HBB'
             )
         AND TRIM(UPPER(CRED.CREDIT_TYPE)) NOT LIKE 'CT%ADDON%'
        THEN SALESTRANS.ACCOUNTING_DATE
        ELSE NULL
    END AS CONNECTION_DT,
    SALESTRANS.GENERIC_DATE_6 AS DISCONNECTION_DT,
    SALESTRANS.GENERIC_ATTRIBUTE_5 AS REASON_CODE,
    CASE
        WHEN TRIM(UPPER(CRED.CREDIT_TYPE)) IN (
                'CT_ADVANCE_BACK_ADJ','CT_ADVANCE_ADJ','CT_MANUAL_ADJ',
                'CT_MANUAL_ADJ_MBB','CT_MANUAL_ADJ_HBB','CT_MANUAL_PAYMENT',
                'CT_VOLUME_ADJ','CT_VOLUME_ADJ_BP','CT_VOLUME_ADJ_BP_MBB','CT_VOLUME_ADJ_BP_HBB'
             )
        THEN SALESTRANS.COMPENSATION_DATE
        ELSE NULL
    END AS ADJUSTMENT_DATE,
    CASE
        WHEN TRIM(UPPER(CRED.CREDIT_TYPE)) LIKE 'CT%ADDON%'
        THEN SALESTRANS.ACCOUNTING_DATE
        ELSE NULL
    END AS ADDON_DATE,
    SALESTRANS.EXTENDED_ATTRIBUTE_4 AS IMEI1,
    SALESTRANS.EXTENDED_ATTRIBUTE_5 AS IMEI2,
    SALESTRANS.EVENT_TYPE_ID AS EVENT_TYPE,
    SALESTRANS.EXTENDED_ATTRIBUTE_6 AS INITAL_MSISDN,
    SALESTRANS.EXTENDED_ATTRIBUTE_7 AS PORTIN_MSISDN,
    SALESTRANS.EXTENDED_ATTRIBUTE_8 AS PLAN_DESCRIPTION,
    SALESTRANS.EXTENDED_ATTRIBUTE_9 AS DEVICE_DESCRITPION,
    SALESTRANS.EXTENDED_ATTRIBUTE_3 AS ICCID,
    SALESTRANS.GENERIC_ATTRIBUTE_9 AS PRODUCT_CODE,
    SALESTRANS.GENERIC_ATTRIBUTE_10 AS PRODUCT_DESC,
    SALESTRANS.GENERIC_ATTRIBUTE_1 AS TARIFF_CODE,
    SALESTRANS.GENERIC_ATTRIBUTE_2 AS TARIFF_DESC,
    SALESTRANS.DATA_SOURCE AS SOURCE,
    SALESTRANS.EXTENDED_ATTRIBUTE_10 AS ADDON_NAME,
    TRIM(SALESTRANS.EXTENDED_ATTRIBUTE_1) AS FIRST_NAME,
    TRIM(SALESTRANS.EXTENDED_ATTRIBUTE_2) AS LAST_NAME,
    SALESTRANS.EXTENDED_ATTRIBUTE_12 AS SOLD_BY_DEALER_CODE,
    SALESTRANS.GENERIC_ATTRIBUTE_20 AS PARTNER_CODE,
    CP.LASTNAME AS PARTNER_NAME,
    CRED.CREDIT_TYPE AS CREDIT_TYPE,
    CRED.CREDIT_NAME AS CREDIT_NAME,
    CRED.COMPENSATION_DATE AS COMPENSATION_DATE,
    CRED.ORDER_ID AS ORDER_ID,
    SALESTRANS.LINE_NUMBER AS LINE_NUMBER,
    SALESTRANS.GENERIC_ATTRIBUTE_24 AS COMMITMENT_TYPE,
    LOB_EVENTS.SERVICETYPE AS BUS_SERVICE_TYPE,
    SALESTRANS.CHANNEL AS CHANNEL,
    SALESTRANS.GENERIC_ATTRIBUTE_23 AS CONTRACT_TYPE,
    SALESTRANS.GENERIC_BOOLEAN_5 AS ADHOC_TRANS,
    SALESTRANS.GENERIC_NUMBER_1 AS TENURE,
    CRED.CREDIT_AMOUNT AS CREDIT_VAL,
    SALESTRANS.VALUE AS TRX_VAL,
    SYSDATE() AS MODIFIED_DATE,
    SALESTRANS.SUBLINE_NUMBER AS SUBLINE_NUMBER,
    CASE
        WHEN TRIM(UPPER(SALESTRANS.EVENT_TYPE_ID)) IN ('ET_CONN_UPFR', 'ET_SMARTY_CONN')
         AND TRIM(UPPER(CRED.GA1_EVENT_DESCRIPTION)) IN ('ACQUISITION')
        THEN 1
        WHEN TRIM(UPPER(SALESTRANS.EVENT_TYPE_ID)) IN ('ET_CONN_UPFR_BACK', 'ET_SMARTY_DISC')
         AND TRIM(UPPER(CRED.GA1_EVENT_DESCRIPTION)) IN ('ACQUISITION')
        THEN -1
        WHEN TRIM(UPPER(SALESTRANS.EVENT_TYPE_ID)) = 'ET_PAYG_NONITU'
         AND SALESTRANS.LINE_NUMBER = 1
        THEN 1
        ELSE 0
    END AS CONNECTIONS,
    LOB_EVENTS.LOB AS LOB,
    TO_CHAR(SYSDATE(), 'IW') AS WEEK_IN_YEAR,
    SALESTRANS.EXTENDED_ATTRIBUTE_16 AS TRIPLE_NET,
    SALESTRANS.GENERIC_ATTRIBUTE_2 AS IND_REP_TARIFF,
    SALESTRANS.GENERIC_NUMBER_4 AS IND_REP_TARIFF_PRICE,
    SALESTRANS.GENERIC_NUMBER_6 AS IND_REP_ADDON_VALUE,
    SALESTRANS.DISCOUNT_TYPE AS IND_REP_DISCOUNT_VALUE,
    SALESTRANS.EXTENDED_ATTRIBUTE_14 AS IND_REP_MRC,
    SALESTRANS.EXTENDED_ATTRIBUTE_15 AS MRC_LESS_VAT,
    SALESTRANS.GENERIC_ATTRIBUTE_15 AS CUSTOMER_TYPE,
    SALESTRANS.COMMENTS AS COMMENTS,
    LOB_EVENTS.BUSINESSTYPE AS BUSINESS_TYPE,
    SALESTRANS.GENERIC_ATTRIBUTE_22 AS SERVICE_TYPE,
    CASE
        WHEN TRIM(UPPER(SALESTRANS.EVENT_TYPE_ID)) IN ('ET_PAYG_NONITU')
        THEN SALESTRANS.COMPENSATION_DATE
        ELSE NULL
    END AS PAYG_TOPUP_DT,
    SALESTRANS.GENERIC_ATTRIBUTE_25 AS TXN_REF_NO,
    SALESTRANS.ACCOUNTING_DATE AS ACCOUNTING_DATE,
    SALESTRANS.BILL_TO_CUST_ID AS BAN,   
    SALESTRANS.GENERIC_ATTRIBUTE_11 AS PRODUCT_GROUP,
    SALESTRANS.GENERIC_ATTRIBUTE_27 AS CHANNEL_FULL_NAME,
    SALESTRANS.GENERIC_ATTRIBUTE_28 AS CUSTOMER_STATUS,
    CRED.GN4_CONTRACT_ACTIVE_DURATION_IN_MONTHS AS TARGETED_MRC,
    CRED.GN1_COHORT_ID AS PARTNER_MARGIN,
    CRED.GN6_PAID_FOR_CONTRACT_DURATION AS DEVICE_COST_PRICE

FROM ATO_ADX_STG.CRD CRED

LEFT JOIN (
    SELECT REMOVEDATE, GENERICATTRIBUTE12, LASTNAME
    FROM ATO_CEG_STG.CS_PARTICIPANT
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY GENERICATTRIBUTE12
        ORDER BY REMOVEDATE DESC
    ) = 1
) CP
  ON CRED.PARTNER_CODE = 'IP_' || CP.GENERICATTRIBUTE12

INNER JOIN ATO_ADX_STG.ORDER_TRANSACTION_DETAILS SALESTRANS
  ON  CRED.ORDER_ID   = SALESTRANS.ORDER_ID
  AND CRED.LINE        = SALESTRANS.LINE_NUMBER
  AND CRED.SUBLINE     = SALESTRANS.SUBLINE_NUMBER
  AND CRED.EVENT_TYPE  = SALESTRANS.EVENT_TYPE_ID
  AND CRED.PERIOD      = SALESTRANS.PERIOD

INNER JOIN (
    SELECT EVENTTYPEID, REMOVEDATE
    FROM ATO_CEG_STG.CS_EVENTTYPE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY EVENTTYPEID
        ORDER BY REMOVEDATE DESC
    ) = 1
) EVENTTYPE
  ON EVENTTYPE.EVENTTYPEID = SALESTRANS.EVENT_TYPE_ID

INNER JOIN PRS_CEG_EXT.LOB_DETAILS LOB_EVENTS
  ON  LOB_EVENTS.EVENT_TYPE   = EVENTTYPE.EVENTTYPEID
  AND LOB_EVENTS.CLASSIFIERNAME = CRED.CREDIT_TYPE

LEFT JOIN ATO_CEG_STG.CS_PERIOD PER
  ON PER.NAME = CRED.PERIOD

WHERE NVL(TRIM(UPPER(CRED.GA1_EVENT_DESCRIPTION)), '~') NOT IN ('VOLUME CNT')
  AND TRIM(UPPER(CRED.CREDIT_TYPE)) NOT IN (
        'CT_PAYG_ITU_EXTRA',
        'CT_PAYG_ITU',
        'CT_PAYG_NONITU_TOPUP1_AMOUNT'
      )
  AND (
        COALESCE(TRIM(UPPER(SALESTRANS.DATA_SOURCE)), '~') NOT IN ('LEGACY')
     OR (
            TRIM(UPPER(SALESTRANS.DATA_SOURCE)) IN ('BUSINESS PAID')
        AND TRIM(UPPER(CRED.CREDIT_TYPE)) IN (
                'CT_VOLUME_ADJ_BP',
                'CT_VOLUME_ADJ_BP_MBB',
                'CT_VOLUME_ADJ_BP_HBB'
            )
        )
      );

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)