# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

query = f"""
TRUNCATE TABLE {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------


query = f"""
INSERT INTO {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES
(
	PARTNER_CODE,
	PERIOD,
	INCENTIVE_GENERATED_DATE,
	INCENTIVE_NAME,
	RULE_TYPE,
	DESCRIPTION,
	SOURCE_MEASUREMENT,
	AMOUNT_TYPE,
	INCENTIVE_AMOUNT,
	INCENTIVE_OUTPUT_NAME,
	UNIT_TYPE,
	PERIOD_TYPE,
	DISPLAY_NAME_FOR_REPORTS,
	GA1_INCENTIVE_TYPE,
	GA2_PM_OR_SM_TO_TRACE_CONTRIBUTING,
	GA3_PM_OR_SM_TO_TRACE_CONTRIBUTING,
	GA4_TIER1_MTDQTDYTD_VALUE,
	GA5_TIER2_MTDQTDYTD_VALUE,
	GA6_TIER3_MTDQTDYTD_VALUE,
	GA7_LD_MTDQTDYTD_VALUE,
	GA16_QUOTA_NAME,
	GN1_TIER1_TARGET,
	GN2_TIER2_TARGET,
	GN3_TIER3_TARGET,
	GN4_LD_TARGET,
	GN5_MTDQTD,
	GN6_YTD,
	INSERT_TS,
	UPDATE_TS
)
SELECT
	SRC.PARTNER_CODE,
	SRC.PERIOD,
	SRC.INCENTIVE_GENERATED_DATE,
	SRC.INCENTIVE_NAME,
	SRC.RULE_TYPE,
	SRC.DESCRIPTION,
	SRC.SOURCE_MEASUREMENT,
	SRC.AMOUNT_TYPE,
	SRC.INCENTIVE_AMOUNT,
	SRC.INCENTIVE_OUTPUT_NAME,
	SRC.UNIT_TYPE,
	SRC.PERIOD_TYPE,
	SRC.DISPLAY_NAME_FOR_REPORTS,
	SRC.GA1_INCENTIVE_TYPE,
	SRC.GA2_PM_OR_SM_TO_TRACE_CONTRIBUTING,
	SRC.GA3_PM_OR_SM_TO_TRACE_CONTRIBUTING,
	SRC.GA4_TIER1_MTDQTDYTD_VALUE,
	SRC.GA5_TIER2_MTDQTDYTD_VALUE,
	SRC.GA6_TIER3_MTDQTDYTD_VALUE,
	SRC.GA7_LD_MTDQTDYTD_VALUE,
	SRC.GA16_QUOTA_NAME,
	SRC.GN1_TIER1_TARGET,
	SRC.GN2_TIER2_TARGET,
	SRC.GN3_TIER3_TARGET,
	SRC.GN4_LD_TARGET,
	SRC.GN5_MTDQTD,
	SRC.GN6_YTD,
	SRC.INSERT_TS,
	SRC.UPDATE_TS
FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES_STG SRC
WHERE SRC.INSERT_TS = (
	SELECT MAX(INSERT_TS)
	FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES_STG
)
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)