# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

# period_name_value = dbutils.widgets.get("PERIOD_NAME")
period_name_value = 'July 2026 M'
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYM_INCENTIVES;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYM_INCENTIVES
(
PARTNER_CODE
,PERIOD
,CURRENT_MONTH_AMOUNT
,QUARTER_TO_DATE
,YEAR_TO_DATE
,MONTH_1_AMOUNT
,MONTH_2_AMOUNT
,MONTH_3_AMOUNT
)
SELECT
    P.PARTNER_CODE,
    P.PERIOD,
    P.CURRENT_MONTH_AMOUNT,

    --QTD
    SUM(P.CURRENT_MONTH_AMOUNT) OVER (PARTITION BY P.PARTNER_CODE, P.QUARTER_START_DATE ORDER BY P.PERIOD_DATE) AS QUARTER_TO_DATE,

    --YTD
    SUM(P.CURRENT_MONTH_AMOUNT) OVER (PARTITION BY P.PARTNER_CODE, P.YEAR_START_DATE ORDER BY P.PERIOD_DATE) AS YEAR_TO_DATE,

    --MONTH-1
    M1.CURRENT_MONTH_AMOUNT AS MONTH_1_AMOUNT,

    --MONTH-2
    M2.CURRENT_MONTH_AMOUNT AS MONTH_2_AMOUNT,

    --MONTH-3
    M3.CURRENT_MONTH_AMOUNT AS MONTH_3_AMOUNT

FROM
(
    SELECT
        PARTNER_CODE,
        PERIOD,
        SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT,
        TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE,
        DATE_TRUNC('QUARTER', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')) AS QUARTER_START_DATE,
        DATE_TRUNC('YEAR', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')) AS YEAR_START_DATE

    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES

    WHERE UPPER(TRIM(INCENTIVE_NAME)) IN
    (
        'IR_MCAL_IP_CMHA_DEVICE','IR_MCAL_IP_CMHA_RECURRING','IR_MCAL_IP_CMHA_TARIFF','IR_MCAL_IP_CMHU_DEVICE','IR_MCAL_IP_CMHU_RECURRING','IR_MCAL_IP_CMHU_TARIFF','IR_MCAL_IP_CMSA_RECURRING','IR_MCAL_IP_CMSA_TARIFF','IR_MCAL_IP_CMSU_RECURRING','IR_MCAL_IP_CMSU_TARIFF','IR_MCAL_IP_CVHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CVHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHA_HANDSETBONUS','IR_MCAL_IP_CVHA_MRCSHARECOMMISSION','IR_MCAL_IP_CVHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHA_USIM','IR_MCAL_IP_CVHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CVHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHU_HANDSETBONUS','IR_MCAL_IP_CVHU_MRCSHARECOMMISSION','IR_MCAL_IP_CVHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVSA','IR_MCAL_IP_CVSA_ADDON','IR_MCAL_IP_CVSU','IR_MCAL_IP_CVSU_ADDON','IR_MCAL_IP_MANUAL_ADJUSTMENT','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP','IR_MCAL_IP_ADVANCE_ADJUSTMENT','IR_MCAL_IP_PAYG_ITU_TOTALREBATE','IR_MCAL_IP_PAYG_NONITU_REBATE','IR_MCAL_IP_PAYG_NONITU_REVSHARE','IR_MCAL_IP_PAYG_NONITU_TOPUP1','IR_MCAL_IP_CMHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CMHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHA_DEVICEBONUS','IR_MCAL_IP_CMHA_MRCSHARECOMMISSION','IR_MCAL_IP_CMHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CMHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHU_DEVICEBONUS','IR_MCAL_IP_CMHU_MRCSHARECOMMISSION','IR_MCAL_IP_CMHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CHHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHA_DEVICEBONUS','IR_MCAL_IP_CHHA_MRCSHARECOMMISSION','IR_MCAL_IP_CHHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CHHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHU_DEVICEBONUS','IR_MCAL_IP_CHHU_MRCSHARECOMMISSION','IR_MCAL_IP_CHHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_MANUAL_ADJUSTMENT_HBB','IR_MCAL_IP_MANUAL_ADJUSTMENT_MBB','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP_MBB','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP_HBB'
    ) AND PERIOD LIKE '%M'

    GROUP BY
        PARTNER_CODE,
        PERIOD,
        TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY'),
        DATE_TRUNC('QUARTER', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')),
        DATE_TRUNC('YEAR', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY'))
) P

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M1
    ON P.PARTNER_CODE = M1.PARTNER_CODE
   AND M1.PERIOD_DATE = DATEADD(MONTH, -1, P.PERIOD_DATE)

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M2
    ON P.PARTNER_CODE = M2.PARTNER_CODE
   AND M2.PERIOD_DATE = DATEADD(MONTH, -2, P.PERIOD_DATE)

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYM_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M3
    ON P.PARTNER_CODE = M3.PARTNER_CODE
   AND M3.PERIOD_DATE = DATEADD(MONTH, -3, P.PERIOD_DATE);

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYG_INCENTIVES;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYG_INCENTIVES
(
PARTNER_CODE
,PERIOD
,CURRENT_MONTH_AMOUNT
,QUARTER_TO_DATE
,YEAR_TO_DATE
,MONTH_1_AMOUNT
,MONTH_2_AMOUNT
,MONTH_3_AMOUNT
)
SELECT
    P.PARTNER_CODE,
    P.PERIOD,
    P.CURRENT_MONTH_AMOUNT,

    --QTD
    SUM(P.CURRENT_MONTH_AMOUNT) OVER (PARTITION BY P.PARTNER_CODE, P.QUARTER_START_DATE ORDER BY P.PERIOD_DATE) AS QUARTER_TO_DATE,

    --YTD
    SUM(P.CURRENT_MONTH_AMOUNT) OVER (PARTITION BY P.PARTNER_CODE, P.YEAR_START_DATE ORDER BY P.PERIOD_DATE) AS YEAR_TO_DATE,

    --MONTH-1
    M1.CURRENT_MONTH_AMOUNT AS MONTH_1_AMOUNT,

    --MONTH-2
    M2.CURRENT_MONTH_AMOUNT AS MONTH_2_AMOUNT,

    --MONTH-3
    M3.CURRENT_MONTH_AMOUNT AS MONTH_3_AMOUNT

FROM
(
    SELECT
        PARTNER_CODE,
        PERIOD,
        SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT,
        TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE,
        DATE_TRUNC('QUARTER', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')) AS QUARTER_START_DATE,
        DATE_TRUNC('YEAR', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')) AS YEAR_START_DATE

    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_INCENTIVES

    WHERE UPPER(TRIM(INCENTIVE_NAME)) IN
    (
        'IR_MCAL_IP_CMHA_DEVICE','IR_MCAL_IP_CMHA_RECURRING','IR_MCAL_IP_CMHA_TARIFF','IR_MCAL_IP_CMHU_DEVICE','IR_MCAL_IP_CMHU_RECURRING','IR_MCAL_IP_CMHU_TARIFF','IR_MCAL_IP_CMSA_RECURRING','IR_MCAL_IP_CMSA_TARIFF','IR_MCAL_IP_CMSU_RECURRING','IR_MCAL_IP_CMSU_TARIFF','IR_MCAL_IP_CVHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CVHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHA_HANDSETBONUS','IR_MCAL_IP_CVHA_MRCSHARECOMMISSION','IR_MCAL_IP_CVHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHA_USIM','IR_MCAL_IP_CVHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CVHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVHU_HANDSETBONUS','IR_MCAL_IP_CVHU_MRCSHARECOMMISSION','IR_MCAL_IP_CVHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CVSA','IR_MCAL_IP_CVSA_ADDON','IR_MCAL_IP_CVSU','IR_MCAL_IP_CVSU_ADDON','IR_MCAL_IP_MANUAL_ADJUSTMENT','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP','IR_MCAL_IP_ADVANCE_ADJUSTMENT','IR_MCAL_IP_PAYG_ITU_TOTALREBATE','IR_MCAL_IP_PAYG_NONITU_REBATE','IR_MCAL_IP_PAYG_NONITU_REVSHARE','IR_MCAL_IP_PAYG_NONITU_TOPUP1','IR_MCAL_IP_CMHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CMHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHA_DEVICEBONUS','IR_MCAL_IP_CMHA_MRCSHARECOMMISSION','IR_MCAL_IP_CMHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CMHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CMHU_DEVICEBONUS','IR_MCAL_IP_CMHU_MRCSHARECOMMISSION','IR_MCAL_IP_CMHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHA_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CHHA_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHA_DEVICEBONUS','IR_MCAL_IP_CHHA_MRCSHARECOMMISSION','IR_MCAL_IP_CHHA_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHU_ADDON_MRCSHARECOMMISSION','IR_MCAL_IP_CHHU_ADDON_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_CHHU_DEVICEBONUS','IR_MCAL_IP_CHHU_MRCSHARECOMMISSION','IR_MCAL_IP_CHHU_MRCSUBSIDYCOMMISSION','IR_MCAL_IP_MANUAL_ADJUSTMENT_HBB','IR_MCAL_IP_MANUAL_ADJUSTMENT_MBB','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP_MBB','IR_MCAL_IP_VOLUME_ADJUSTMENT_BP_HBB'
    ) AND PERIOD LIKE '%M'

    GROUP BY
        PARTNER_CODE,
        PERIOD,
        TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY'),
        DATE_TRUNC('QUARTER', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')),
        DATE_TRUNC('YEAR', TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY'))
) P

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M1
    ON P.PARTNER_CODE = M1.PARTNER_CODE
   AND M1.PERIOD_DATE = DATEADD(MONTH, -1, P.PERIOD_DATE)

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M2
    ON P.PARTNER_CODE = M2.PARTNER_CODE
   AND M2.PERIOD_DATE = DATEADD(MONTH, -2, P.PERIOD_DATE)

LEFT JOIN
(
    SELECT
        PARTNER_CODE, SUM(INCENTIVE_AMOUNT) AS CURRENT_MONTH_AMOUNT, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY') AS PERIOD_DATE
    FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_INCENTIVES
    WHERE PERIOD LIKE '%M'
    GROUP BY PARTNER_CODE, PERIOD, TO_DATE(REPLACE(PERIOD,' M',''),'MON YYYY')
) M3
    ON P.PARTNER_CODE = M3.PARTNER_CODE
   AND M3.PERIOD_DATE = DATEADD(MONTH, -3, P.PERIOD_DATE);

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.PROPOSED_COMMISSION
--WHERE PERIODNAME = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M';
WHERE PERIODNAME = '{period_name_value}'

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.PROPOSED_COMMISSION
(
PAYEENAME,
PERIOD_START_DATE,
PERIOD_END_DATE,
PERIODNAME,
CURRENT_MONTH,
QTD,
YTD,
MONTH_1,
MONTH_2,
MONTH_3,
PARTICIPANTID,
INV_CNT
)
SELECT
TLR.PAYEENAME,
TLR.PERIOD_START_DATE,
TLR.PERIOD_END_DATE,
TLR.PERIODNAME,
TLR.CURRENT_MONTH,
TLR.QTD,
TLR.YTD,
TLR.MONTH_1,
TLR.MONTH_2,
TLR.MONTH_3,
TLR.PARTICIPANTID,
TLR.INV_CNT
FROM
(
SELECT
    PAR.LASTNAME AS PAYEENAME, 
    PRD.STARTDATE   AS PERIOD_START_DATE,
    DATEADD(DAY,-1,PRD.ENDDATE)  AS PERIOD_END_DATE,
    PRD.NAME  AS PERIODNAME,
    INC.CURRENT_MONTH  AS CURRENT_MONTH,
    INC.QTD  AS QTD,
    INC.YTD  AS YTD,
    INC.MONTH_1  AS MONTH_1,
    INC.MONTH_2  AS MONTH_2,
    INC.MONTH_3  AS MONTH_3,
    INC.PARTNER_CODE  AS PARTICIPANTID,
    CASE
		WHEN INC.CURRENT_MONTH <> 0 THEN 1
        ELSE 0
    END AS INV_CNT
FROM
(
        SELECT
            U.PARTNER_CODE,
            U.PERIOD,
            SUM(U.CURRENT_MONTH) AS CURRENT_MONTH,
            SUM(U.QTD) AS QTD,
            SUM(U.YTD) AS YTD,
            SUM(U.MONTH_1) AS MONTH_1,
            SUM(U.MONTH_2) AS MONTH_2,
            SUM(U.MONTH_3) AS MONTH_3
        FROM
        (
SELECT
	PARTNER_CODE,
	PERIOD,
	CURRENT_MONTH_AMOUNT AS CURRENT_MONTH,
	QUARTER_TO_DATE AS QTD , 
	YEAR_TO_DATE AS YTD, 
	MONTH_1_AMOUNT AS MONTH_1,
	MONTH_2_AMOUNT AS MONTH_2, 
	MONTH_3_AMOUNT AS MONTH_3
	
	FROM {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYM_INCENTIVES
	--WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    WHERE PERIOD = '{period_name_value}'
	
UNION ALL

SELECT
	PARTNER_CODE,
	PERIOD,
	CURRENT_MONTH_AMOUNT AS CURRENT_MONTH,
	QUARTER_TO_DATE AS QTD , 
	YEAR_TO_DATE AS YTD, 
	MONTH_1_AMOUNT AS MONTH_1,
	MONTH_2_AMOUNT AS MONTH_2, 
	MONTH_3_AMOUNT AS MONTH_3
	
	FROM {sfDatabase}.ATO_CEG_STG.PROPOSED_COMMISSION_AGGR_PAYG_INCENTIVES
	WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    ) U
        GROUP BY U.PARTNER_CODE, U.PERIOD
) INC

INNER JOIN
(
    SELECT GENERICATTRIBUTE12, LASTNAME
    FROM {sfDatabase}.ATO_CEG_STG.CS_PARTICIPANT
	QUALIFY ROW_NUMBER() OVER (PARTITION BY GENERICATTRIBUTE12 ORDER BY REMOVEDATE DESC) = 1
) PAR
ON INC.PARTNER_CODE = 'IP_' || PAR.GENERICATTRIBUTE12

INNER JOIN
(
    SELECT STARTDATE, ENDDATE, NAME
    FROM {sfDatabase}.ATO_CEG_STG.CS_PERIOD
    QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY REMOVEDATE DESC) = 1
) PRD
    ON INC.PERIOD = PRD.NAME
) TLR;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()