# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.ATO_CEG_STG.CALLIDUS_THREEUK_COMM_CREDITS
(
PAYMENT_RUN_NUMBER,
PARTICIPANT_ID,
PARTICIPANT_AR_CUSTOMER_NUMBER,
PARTICIPANT_AP_SUPPLIER_NUMBER,
PARTICIPANT_NAME,
PARTICIPANT_VAT_STATUS,
PARTICIPANT_VAT_NUMBER,
DOC_NUMBER,
DOC_DATE,
DOC_TYPE,
DOC_LINE_TYPE,
DOC_LINE_TEXT,
CALLIDUS_ORDER_NUMBER,
CALLIDUS_ORDER_LINE_NUMBER,
CALLIDUS_ORDER_SUBLINE_NUMBER,
CALLIDUS_EVENTTYPE,
CALLIDUS_COMPENSATION_DATE,
CREDITTYPE,
EARNINGS_GROUP,
PAYMENT_VALUE_EXVAT,
PAYMENT_OR_CLAWBACK
)
SELECT
COCC.PAYMENT_RUN_NO AS PAYMENT_RUN_NUMBER,
'IP_' || COCC.PARTICIPANT_ID AS PARTICIPANT_ID,
COCC.ACCOUNT_RECV_REF AS PARTICIPANT_AR_CUSTOMER_NUMBER,
COCC.ACCOUNT_PAY_REF AS PARTICIPANT_AP_SUPPLIER_NUMBER,
COCC.PARTNER_NAME AS PARTICIPANT_NAME,
CASE
    WHEN COCC.VAT_LOCATION IS NULL THEN 'N'
    ELSE 'Y'
END AS PARTICIPANT_VAT_STATUS,
COCC.VAT_NO AS PARTICIPANT_VAT_NUMBER,
COCC.DOCNO AS DOC_NUMBER,
TO_CHAR(COCC.DOC_DATE, 'YYYYMMDD') AS DOC_DATE,
COCC.PAYMENT_DOC_TYPE AS DOC_TYPE,
COCC.PAYDOCLINETYPE AS DOC_LINE_TYPE,
COCC.PAYDOCLINETYPEDESC AS DOC_LINE_TEXT,
COCC.ORDERID AS CALLIDUS_ORDER_NUMBER,
COCC.LINENUMBER AS CALLIDUS_ORDER_LINE_NUMBER,
COCC.SUBLINENUMBER AS CALLIDUS_ORDER_SUBLINE_NUMBER,
COCC.EVENTTYPE AS CALLIDUS_EVENTTYPE,
TO_CHAR(COCC.COMPENSATIONDATE, 'YYYYMMDD') AS CALLIDUS_COMPENSATION_DATE,
COCC.CREDITTYPEID AS CREDITTYPE,
COCC.PAYDOCLINETYPE AS EARNINGS_GROUP,
COCC.CREDIT_VALUE AS PAYMENT_VALUE_EXVAT,
COCC.PAYMENT_TYPE AS PAYMENT_OR_CLAWBACK

FROM {sfDatabase}.ATO_CEG_STG.CALLIDUS_OUT_COMM_CREDITS COCC;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()