# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

period_name_value = dbutils.widgets.get("PERIOD_NAME")
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_DETAIL_STATEMENT
--WHERE PERIOD_NAME = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
WHERE PERIOD_NAME = '{period_name_value}'
;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_DETAIL_STATEMENT (
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    CONNECTION_ID,
    CONNECTION_DT,
    DISCONNECTION_DT,
    REASON_CODE,
    ADJUSTMENT_DATE,
    ADDON_DATE,
    IMEI1,
    IMEI2,
    ICCID,
    EVENT_TYPE,
    INITIAL_MSISDN,
    PORTIN_MSISDN,
    PRODUCT_CODE,
    PRODUCT_DESC,
    SOURCE,
    TARIFF_CODE,
    TARIFF_DESC,
    ADDON_NAME,
    FIRST_NAME,
    LAST_NAME,
    SOLD_BY_DEALER_CODE,
    PARTNER_CODE,
    PARTNER_NAME,
    ORDER_ID,
    LINE_NUMBER,
    COMMITMENT_TYPE,
    SERVICE_TYPE,
    ADHOC_TRANS,
    TARIFF_BONUS,
    PROMOTION_BONUS,
    MRCSHARE_BONUS,
    ADVANCE_PAYMENT_BONUS,
    USIM_REFUND,
    MISCELLANEOUS,
    VOLUME_BONUS,
    TACTICAL_BONUS,
    TOTAL_PAYMENT,
    CONNECTIONS,
    COMMENTS,
    IS_POSTED,
    IS_FINALIZED,
    MODIFIED_DATE,
    TENURE,
    ADDON_BONUS,
    MRCSUBSIDY_BONUS,
    ADDON_MRCSHARE_BONUS,
    ADDON_MRCSUBS_BONUS,
    CONTRACT_TYPE,
    SUBLINE_NUMBER,
    PAYG_TOPUP_BONUS,
    PAYG_REVSHARE,
    PAYG_REBATE,
    LOB,
    BUSINESS_TYPE,
    BUS_SERVICE_TYPE,
    PAYG_TOPUP_DT,
    TXN_REF_NO,
    BAN,
    CHANNEL,
    CHANNEL_FULL_NAME,
    CUSTOMER_STATUS
)
SELECT
    B2C_DEALER_DETAILS.PERIOD_NAME,
    B2C_DEALER_DETAILS.PERIOD_START_DATE,
    B2C_DEALER_DETAILS.PERIOD_END_DATE,
    B2C_DEALER_DETAILS.CONNECTION_ID,
    B2C_DEALER_DETAILS.CONNECTION_DT,
    B2C_DEALER_DETAILS.DISCONNECTION_DT,
    B2C_DEALER_DETAILS.REASON_CODE,
    B2C_DEALER_DETAILS.ADJUSTMENT_DATE,
    B2C_DEALER_DETAILS.ADDON_DATE,
    B2C_DEALER_DETAILS.IMEI1,
    B2C_DEALER_DETAILS.IMEI2,
    B2C_DEALER_DETAILS.ICCID,
    B2C_DEALER_DETAILS.EVENT_TYPE,
    B2C_DEALER_DETAILS.INITAL_MSISDN AS INITIAL_MSISDN,
    B2C_DEALER_DETAILS.PORTIN_MSISDN,
    B2C_DEALER_DETAILS.PRODUCT_CODE,
    B2C_DEALER_DETAILS.PRODUCT_DESC,
    B2C_DEALER_DETAILS.SOURCE,
    B2C_DEALER_DETAILS.TARIFF_CODE,
    B2C_DEALER_DETAILS.TARIFF_DESC,
    NVL(B2C_DEALER_DETAILS.ADDON_NAME, TO_CHAR(B2C_DEALER_DETAILS.IND_REP_ADDON_VALUE)) AS ADDON_NAME,
    B2C_DEALER_DETAILS.FIRST_NAME,
    B2C_DEALER_DETAILS.LAST_NAME,
    B2C_DEALER_DETAILS.SOLD_BY_DEALER_CODE,
    B2C_DEALER_DETAILS.PARTNER_CODE,
    B2C_DEALER_DETAILS.PARTNER_NAME,
    B2C_DEALER_DETAILS.ORDER_ID,
    B2C_DEALER_DETAILS.LINE_NUMBER,
    B2C_DEALER_DETAILS.COMMITMENT_TYPE,
    B2C_DEALER_DETAILS.SERVICE_TYPE,
    B2C_DEALER_DETAILS.ADHOC_TRANS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) NOT LIKE 'CT%ADDON%'
         AND (
                trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%TARIFF%'
             OR trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%RECURRING%'
             OR trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%MONTHLY_RENEWAL%'
             OR trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                    'CT_SMARTY_PAYMENTACTIVATION_BACK',
                    'CT_SMARTY_PAYMENTACTIVATION',
                    'CT_SMARTY_DATA_PAYMENTACTIVATION'
                )
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS TARIFF_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%DEVICE%'
          OR trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%HANDSET%'
          OR trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_OMRC_RENEWAL_CONNECTION',
                'CT_OMRC_RENEWAL_CONNECTION_BACK',
                'CT_SMARTY_PAYMENTFIRSTRENEWAL',
                'CT_SMARTY_DATA_PAYMENTFIRSTRENEWAL',
                'CT_SMARTY_FIRSTRENEWAL_BACK'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS PROMOTION_BONUS,
    MAX(CASE
        WHEN (
                trim(upper(B2C_DEALER_DETAILS.credit_type)) NOT LIKE 'CT%ADDON%'
            AND trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%MRCSHARE%'
             )
          OR trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_SMARTY_PAYMENT_SUBRENEWAL',
                'CT_SMARTY_DATA_PAYMENT_SUBRENEWAL',
                'CT_SMARTY_PAYMENTSUBRENEWAL_BACK'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS MRCSHARE_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN ('CT_ADVANCE_BACK_ADJ', 'CT_ADVANCE_ADJ')
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS ADVANCE_PAYMENT_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%USIM%'
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS USIM_REFUND,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT_MANUAL%'
          OR trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT_VOLUME_ADJ_BP%'
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS MISCELLANEOUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT_VOLUME_ADJ%'
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS VOLUME_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) = 'CT_CMHA_TACTICAL'
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS TACTICAL_BONUS,
    SUM(B2C_DEALER_DETAILS.CREDIT_VAL) AS TOTAL_PAYMENT,
    MAX(B2C_DEALER_DETAILS.CONNECTIONS) AS CONNECTIONS,
    MAX(B2C_DEALER_DETAILS.COMMENTS) AS COMMENTS,
    MAX(0) AS IS_POSTED,
    MAX(0) AS IS_FINALIZED,
    MAX(SYSDATE()) AS MODIFIED_DATE,
    B2C_DEALER_DETAILS.TENURE,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) NOT IN (
                'CT_CVHA_ADDON_MRCSHARE','CT_CVHA_ADDON_SUBSIDY','CT_CVHU_ADDON_MRCSHARE','CT_CVHU_ADDON_SUBSIDY',
                'CT_CVHA_ADDON_MRCSHARE_BACK','CT_CVHA_ADDON_SUBSIDY_BACK','CT_CVHU_ADDON_MRCSHARE_BACK','CT_CVHU_ADDON_SUBSIDY_BACK',
                'CT_CMHA_ADDON_MRCSHARE','CT_CMHA_ADDON_SUBSIDY','CT_CMHU_ADDON_MRCSHARE','CT_CMHU_ADDON_SUBSIDY',
                'CT_CMHA_ADDON_MRCSHARE_BACK','CT_CMHA_ADDON_SUBSIDY_BACK','CT_CMHU_ADDON_MRCSHARE_BACK','CT_CMHU_ADDON_SUBSIDY_BACK',
                'CT_CHHA_ADDON_MRCSHARE','CT_CHHA_ADDON_SUBSIDY','CT_CHHU_ADDON_MRCSHARE','CT_CHHU_ADDON_SUBSIDY',
                'CT_CHHA_ADDON_MRCSHARE_BACK','CT_CHHA_ADDON_SUBSIDY_BACK','CT_CHHU_ADDON_MRCSHARE_BACK','CT_CHHU_ADDON_SUBSIDY_BACK',
                'CT_CMHA_PARTIAL_ADDON_MRCSHARE_BACK','CT_CMHA_PARTIAL_ADDON_SUBSIDY_BACK',
                'CT_CMHU_PARTIAL_ADDON_MRCSHARE_BACK','CT_CMHU_PARTIAL_ADDON_SUBSIDY_BACK',
                'CT_CHHA_PARTIAL_ADDON_MRCSHARE_BACK','CT_CHHA_PARTIAL_ADDON_SUBSIDY_BACK',
                'CT_CHHU_PARTIAL_ADDON_MRCSHARE_BACK','CT_CHHU_PARTIAL_ADDON_SUBSIDY_BACK'
             )
         AND trim(upper(B2C_DEALER_DETAILS.credit_type)) LIKE 'CT%ADDON%'
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS ADDON_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_CVHA_SUBSIDY','CT_CVHU_SUBSIDY','CT_CVHA_SUBSIDY_BACK','CT_CVHU_SUBSIDY_BACK',
                'CT_CMHA_SUBSIDY','CT_CMHU_SUBSIDY','CT_CMHA_SUBSIDY_BACK','CT_CMHU_SUBSIDY_BACK',
                'CT_CHHA_SUBSIDY','CT_CHHU_SUBSIDY','CT_CHHA_SUBSIDY_BACK','CT_CHHU_SUBSIDY_BACK',
                'CT_CMHA_PARTIAL_SUBSIDY_BACK','CT_CMHU_PARTIAL_SUBSIDY_BACK',
                'CT_CHHA_PARTIAL_SUBSIDY_BACK','CT_CHHU_PARTIAL_SUBSIDY_BACK',
                'CT_SMARTY_LEGACY_COMMISSION_BACK'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS MRCSUBSIDY_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_CVHA_ADDON_MRCSHARE','CT_CVHU_ADDON_MRCSHARE','CT_CVHA_ADDON_MRCSHARE_BACK','CT_CVHU_ADDON_MRCSHARE_BACK',
                'CT_CMHA_ADDON_MRCSHARE','CT_CMHU_ADDON_MRCSHARE','CT_CMHA_ADDON_MRCSHARE_BACK','CT_CMHU_ADDON_MRCSHARE_BACK',
                'CT_CHHA_ADDON_MRCSHARE','CT_CHHU_ADDON_MRCSHARE','CT_CHHA_ADDON_MRCSHARE_BACK','CT_CHHU_ADDON_MRCSHARE_BACK',
                'CT_CMHA_PARTIAL_ADDON_MRCSHARE_BACK','CT_CMHU_PARTIAL_ADDON_MRCSHARE_BACK',
                'CT_CHHA_PARTIAL_ADDON_MRCSHARE_BACK','CT_CHHU_PARTIAL_ADDON_MRCSHARE_BACK'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS ADDON_MRCSHARE_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_CVHA_ADDON_SUBSIDY','CT_CVHU_ADDON_SUBSIDY','CT_CVHA_ADDON_SUBSIDY_BACK','CT_CVHU_ADDON_SUBSIDY_BACK',
                'CT_CMHA_ADDON_SUBSIDY','CT_CMHU_ADDON_SUBSIDY','CT_CMHA_ADDON_SUBSIDY_BACK','CT_CMHU_ADDON_SUBSIDY_BACK',
                'CT_CHHA_ADDON_SUBSIDY','CT_CHHU_ADDON_SUBSIDY','CT_CHHA_ADDON_SUBSIDY_BACK','CT_CHHU_ADDON_SUBSIDY_BACK',
                'CT_CMHA_PARTIAL_ADDON_SUBSIDY_BACK','CT_CMHU_PARTIAL_ADDON_SUBSIDY_BACK',
                'CT_CHHA_PARTIAL_ADDON_SUBSIDY_BACK','CT_CHHU_PARTIAL_ADDON_SUBSIDY_BACK'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS ADDON_MRCSUBS_BONUS,
    B2C_DEALER_DETAILS.CONTRACT_TYPE,
    B2C_DEALER_DETAILS.SUBLINE_NUMBER,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN ('CT_PAYG_NONITU_TOPUP1')
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS PAYG_TOPUP_BONUS,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN ('CT_PAYG_NONITU_REVSHARE')
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS PAYG_REVSHARE,
    MAX(CASE
        WHEN trim(upper(B2C_DEALER_DETAILS.credit_type)) IN (
                'CT_PAYG_ITU_REBATE',
                'CT_PAYG_ITU_ENHANCED_REBATE',
                'CT_PAYG_NONITU_REBATE'
             )
        THEN B2C_DEALER_DETAILS.CREDIT_VAL
    END) AS PAYG_REBATE,
    B2C_DEALER_DETAILS.LOB,
    B2C_DEALER_DETAILS.BUSINESS_TYPE,
    B2C_DEALER_DETAILS.BUS_SERVICE_TYPE AS BUS_SERVICE_TYPE,
    B2C_DEALER_DETAILS.PAYG_TOPUP_DT,
    B2C_DEALER_DETAILS.TXN_REF_NO,
    B2C_DEALER_DETAILS.BAN,
    B2C_DEALER_DETAILS.CHANNEL,
    B2C_DEALER_DETAILS.Channel_Full_Name,
    B2C_DEALER_DETAILS.CUSTOMER_STATUS AS Customer_Status
FROM {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_DETAILS
--WHERE PERIOD_NAME = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
--WHERE PERIOD_NAME  = '{period_name_value}'
GROUP BY
    --CALENDAR_NAME,
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
	--PIPELINERUNSEQ,
    BUSINESS_TYPE,
    BUS_SERVICE_TYPE,
    CONNECTION_ID,
    CONNECTION_DT,
    DISCONNECTION_DT,
    REASON_CODE,
    ADJUSTMENT_DATE,
    ADDON_DATE,
    IMEI1,
    IMEI2,
    ICCID,
    LOB,
    EVENT_TYPE,
    INITAL_MSISDN,
    PORTIN_MSISDN,
    PRODUCT_CODE,
    PRODUCT_DESC,
    SOURCE,
    TARIFF_CODE,
    TARIFF_DESC,
    ADDON_NAME,
    IND_REP_Addon_Value,
    FIRST_NAME,
    LAST_NAME,
    SOLD_BY_DEALER_CODE,
    PARTNER_CODE,
    PARTNER_NAME,
    ORDER_ID,
    LINE_NUMBER,
    SUBLINE_NUMBER,
    CONTRACT_TYPE,
    COMMITMENT_TYPE,
    SERVICE_TYPE,
    ADHOC_TRANS,
    TENURE,
    -- ACCOUNTNO,
    PAYG_TOPUP_DT,
    TXN_REF_NO,
    BAN,
    CHANNEL,
    Channel_Full_Name,
    CUSTOMER_STATUS
ORDER BY
    PRODUCT_DESC,
    TARIFF_CODE;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)