# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

#period_name_value = dbutils.widgets.get("PERIOD_NAME") 
period_name_value = "April 2026 M"
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.PAYG_TOPUP_COHORT
--WHERE PERIOD_NAME = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
WHERE PERIOD_NAME = '{period_name_value}'
;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

CREATE OR REPLACE TEMP TABLE {sfDatabase}.ATO_ADX_STG.PAYG_COHORT_TEMP AS 
SELECT 
TLR.PERIOD_NAME
,CSP.STARTDATE AS PERIOD_START_DATE
,DATEADD(DAY, -1, CSP.ENDDATE) AS PERIOD_END_DATE
,TLR.ACQ_SIM_SKU
,'Non-ITU' AS ACQ_ITU
,TLR.MSISDN
,TLR.ICCID
,TLR.ACQ_DATE_SUBSCRIBER
,TLR.ACQ_ORDER_DEALER_KEY
,TLR.ACQ_SITE_NAME
,TLR.RECHARGE_DATE
,TLR.RECHARGE_METHOD_MAIN_ID
,TLR.RECHARGE_METHOD_DESC
,TLR.TOPUP_AMOUNT
,TLR.RECHARGE_KEY
,TLR.ACTIVATION_MONTH
,TLR.COHORT_MONTH
,TLR.TOP_UP_MONTH
,MONTHS_BETWEEN(CSP.STARTDATE, TLR.ACQ_DATE_SUBSCRIBER) + 1 AS DURATION_OF_COMMISSION
,CRD.CREDIT_AMOUNT AS FTU_BONUS
,CRD1.GN2_PAYG_REV_SHARE_RATE AS REV_SHARE_PERC
,ROUND(NVL(TLR.TOPUP_AMOUNT, 0) / (1 + NVL(PARTY.GENERICNUMBER1, 0)), 2) AS TOPUP_AMOUNT_MINUS_VAT
,CRD1.CREDIT_AMOUNT AS REV_SHARE_COMMISSION 
,NVL(CRD.CREDIT_AMOUNT,0) + NVL(CRD1.CREDIT_AMOUNT,0) AS COMMISSIONS_PAYOUT_TOTAL

FROM
(
SELECT
PSA.PERIOD AS PERIOD_NAME
,PSA.GENERIC_ATTRIBUTE_1 AS ACQ_SIM_SKU
,PSA.EXTENDED_ATTRIBUTE_6 AS MSISDN
,PSA.EXTENDED_ATTRIBUTE_3 AS ICCID
,PSA.ACCOUNTING_DATE AS ACQ_DATE_SUBSCRIBER
,PSA.GENERIC_ATTRIBUTE_20 AS ACQ_ORDER_DEALER_KEY
,PSA.GENERIC_ATTRIBUTE_21 AS ACQ_SITE_NAME
,PSA.GENERIC_DATE_6 AS RECHARGE_DATE
,PSA.GENERIC_ATTRIBUTE_25 AS RECHARGE_METHOD_MAIN_ID
,PSA.GENERIC_ATTRIBUTE_26 AS RECHARGE_METHOD_DESC
,PSA.VALUE AS TOPUP_AMOUNT
,PSA.GENERIC_ATTRIBUTE_7 AS RECHARGE_KEY
,PSA.ACCOUNTING_DATE AS ACTIVATION_MONTH
,TO_CHAR(PSA.ACCOUNTING_DATE, 'Mon-YYYY') AS COHORT_MONTH
,PSA.GENERIC_DATE_6 AS TOP_UP_MONTH
,PSA.ORDER_ID AS ORDER_ID
,PSA.LINE_NUMBER AS LINE_NUMBER
,PSA.SUBLINE_NUMBER AS SUBLINE_NUMBER
,PSA.EVENT_TYPE_ID  AS EVENT_TYPE_ID

FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_SALES_ACTIVITY PSA
WHERE TRIM(UPPER(PSA.EVENT_TYPE_ID)) = 'ET_PAYG_NONITU'
--AND PSA.PERIOD = TO_VARCHAR(DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
AND PSA.PERIOD = '{period_name_value}'
) TLR 
	  
LEFT JOIN 
(
SELECT NAME, REMOVEDATE, STARTDATE, ENDDATE
FROM {sfDatabase}.ATO_CEG_STG.CS_PERIOD
QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY REMOVEDATE DESC) = 1
) CSP
ON TLR.PERIOD_NAME = CSP.NAME

LEFT JOIN 
(
SELECT CREDIT_NAME, CREDIT_TYPE, ORDER_ID, LINE, SUBLINE, EVENT_TYPE, PERIOD, CREDIT_AMOUNT 
FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_CREDITS 
WHERE TRIM(UPPER(CREDIT_NAME)) = 'CR_MCAL_IP_PAYG_NONITU_TOPUP1'
AND TRIM(UPPER(CREDIT_TYPE)) = 'CT_PAYG_NONITU_TOPUP1'
) CRD
ON TLR.ORDER_ID = CRD.ORDER_ID
AND TLR.LINE_NUMBER = CRD.LINE
AND TLR.SUBLINE_NUMBER = CRD.SUBLINE
AND TLR.EVENT_TYPE_ID = CRD.EVENT_TYPE
AND TLR.PERIOD_NAME = CRD.PERIOD

LEFT JOIN 
(
SELECT CREDIT_TYPE, CREDIT_NAME, ORDER_ID, LINE, SUBLINE, EVENT_TYPE, PERIOD, GN2_PAYG_REV_SHARE_RATE, CREDIT_AMOUNT 
FROM {sfDatabase}.ATO_CEG_STG.TBL_FACT_PAYG_CREDITS 
WHERE TRIM(UPPER(CREDIT_NAME)) = 'CR_MCAL_IP_PAYG_NONITU_REVSHARE'
AND TRIM(UPPER(CREDIT_TYPE)) = 'CT_PAYG_NONITU_REVSHARE'
) CRD1
ON TLR.ORDER_ID = CRD1.ORDER_ID
AND TLR.LINE_NUMBER = CRD1.LINE
AND TLR.SUBLINE_NUMBER = CRD1.SUBLINE
AND TLR.EVENT_TYPE_ID = CRD1.EVENT_TYPE
AND TLR.PERIOD_NAME = CRD1.PERIOD

LEFT JOIN
(
SELECT GENERICATTRIBUTE12, GENERICNUMBER1, REMOVEDATE 
FROM {sfDatabase}.ATO_CEG_STG.CS_PARTICIPANT
QUALIFY ROW_NUMBER() OVER( PARTITION BY GENERICATTRIBUTE12 ORDER BY REMOVEDATE DESC) = 1
) PARTY
ON 'IP_' || PARTY.GENERICATTRIBUTE12 = TLR.ACQ_ORDER_DEALER_KEY
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.PAYG_TOPUP_COHORT
SELECT
	 PERIOD_NAME 
	,PERIOD_START_DATE 
	,PERIOD_END_DATE 
	,ACQ_SIM_SKU 
	,ACQ_ITU 
	,MSISDN 
	,ICCID 
	,ACQ_DATE_SUBSCRIBER 
	,ACQ_ORDER_DEALER_KEY
	,ACQ_SITE_NAME 
	,RECHARGE_DATE 
	,RECHARGE_METHOD_MAIN_ID 
	,RECHARGE_METHOD_DESC 
	,TOPUP_AMOUNT 
	,RECHARGE_KEY 
	,ACTIVATION_MONTH
	,COHORT_MONTH 
	,TOP_UP_MONTH 
	,DURATION_OF_COMMISSION 
	,FTU_BONUS 
	,REV_SHARE_PERC 
	,TOPUP_AMOUNT_MINUS_VAT 
	,REV_SHARE_COMMISSION 
	,COMMISSIONS_PAYOUT_TOTAL
	,CURRENT_DATE AS EXTRACT_RUN_DATE
FROM {sfDatabase}.ATO_ADX_STG.PAYG_COHORT_TEMP
WHERE EXTRACT_RUN_DATE = CURRENT_DATE()
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()