# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

period_name_value = dbutils.widgets.get("PERIOD_NAME")
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.INDIRECT_COMMISSION_EXCEPTION
--WHERE PERIOD = TO_CHAR(ADD_MONTHS(CURRENT_DATE,-1),'MMMM YYYY') || ' M'
WHERE PERIOD = '{period_name_value}'
;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

/*=========================================================
STEP 1 : ORDER_TRANSACTION_DETAILS
=========================================================*/

CREATE OR REPLACE TEMP TABLE ATO_CEG_STG.ORDER_TRANSACTION_DETAILS AS
SELECT * FROM ATO_CEG_STG.tbl_fact_paym_sales_activity
--WHERE PERIOD = TO_CHAR(ADD_MONTHS(CURRENT_DATE,-1),'MMMM YYYY') || ' M'
WHERE PERIOD = '{period_name_value}'

UNION

SELECT * FROM ATO_CEG_STG.tbl_fact_payg_sales_activity
--WHERE PERIOD = TO_CHAR(ADD_MONTHS(CURRENT_DATE,-1),'MMMM YYYY') || ' M'
WHERE PERIOD = '{period_name_value}'
;


"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

/*=========================================================
STEP 2 : CRD
=========================================================*/

CREATE OR REPLACE TEMP TABLE ATO_CEG_STG.CRD AS
SELECT * FROM ATO_CEG_STG.tbl_fact_paym_credits
UNION
SELECT * FROM ATO_CEG_STG.tbl_fact_payg_credits
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

/*=========================================================
STEP 3 : SALES_TRANSACTION
=========================================================*/

CREATE OR REPLACE TEMP TABLE ATO_CEG_STG.SALES_TRANSACTION AS

SELECT * FROM (
	SELECT SALESTRANS.*
	FROM ATO_CEG_STG.ORDER_TRANSACTION_DETAILS SALESTRANS

	LEFT JOIN ATO_CEG_STG.CRD C
	ON SALESTRANS.ORDER_ID			= C.ORDER_ID
	AND SALESTRANS.LINE_NUMBER		= C.LINE
	AND SALESTRANS.SUBLINE_NUMBER	= C.SUBLINE
	AND SALESTRANS.EVENT_TYPE_ID	= C.EVENT_TYPE
	AND SALESTRANS.PERIOD			= C.PERIOD
	AND UPPER(C.CREDIT_TYPE) NOT IN ('CT_PAYG_NONITU_TOPUP2_AMOUNT', 'CT_PAYG_NONITU_TOPUP1_AMOUNT', 'CT_PAYG_NONITU_TOPUP_AMOUNT', 'CT_PAYG_ITU')

	WHERE UPPER(SALESTRANS.DATA_SOURCE) NOT IN ('LEGACY','BUSINESS PAID')
	AND UPPER(SALESTRANS.EVENT_TYPE_ID) IN ('ET_CONN_UPFR', 'ET_CONN_UPFR_BACK', 'ET_BILL_INVO', 'ET_TRUEUP', 'ET_PAYG_NONITU', 'ET_PAYG_ITU_SHIPMENT', 'ET_PAYG_NONITU_SHIPMENT')
	AND C.ORDER_ID IS NULL
)

UNION ALL

SELECT DISTINCT * FROM (
	SELECT SALESTRANS.*
	FROM ATO_CEG_STG.ORDER_TRANSACTION_DETAILS SALESTRANS

	LEFT JOIN ATO_CEG_STG.CRD C
	ON SALESTRANS.ORDER_ID			= C.ORDER_ID
	AND SALESTRANS.LINE_NUMBER		= C.LINE
	AND SALESTRANS.SUBLINE_NUMBER	= C.SUBLINE
	AND SALESTRANS.EVENT_TYPE_ID	= C.EVENT_TYPE
	AND SALESTRANS.PERIOD			= C.PERIOD
	AND UPPER(C.CREDIT_TYPE) NOT IN ('CT_PAYG_NONITU_TOPUP2_AMOUNT', 'CT_PAYG_NONITU_TOPUP1_AMOUNT', 'CT_PAYG_NONITU_TOPUP_AMOUNT', 'CT_PAYG_ITU')
	AND C.CREDIT_AMOUNT <= 0

	WHERE UPPER(SALESTRANS.DATA_SOURCE) NOT IN ('LEGACY','BUSINESS PAID')
	AND UPPER(SALESTRANS.EVENT_TYPE_ID) IN ('ET_CONN_UPFR', 'ET_BILL_INVO', 'ET_TRUEUP', 'ET_PAYG_NONITU', 'ET_PAYG_ITU_SHIPMENT', 'ET_PAYG_NONITU_SHIPMENT')
)
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

/*=========================================================
FINAL TARGET LOAD
=========================================================*/

INSERT INTO {sfDatabase}.PRS_CEG_EXT.INDIRECT_COMMISSION_EXCEPTION
(
	COMPENSATION_DATE,
	ACCOUNTING_DATE,
	ORDER_ID,
	LINE_NUMBER,
	SUBLINE_NUMBER,
	SOURCE,
	EQUIPMENT_SOURCED,
	EVENT_TYPE,
	CONTRACT_TYPE,
	COMMITMENT_TYPE,
	SERVICE_TYPE,
	CHANNEL,
	LOOKUP_NAME,
	IMEI1,
	IMEI2,
	INITIAL_MSISDN,
	PORTIN_MSISDN,
	PARTNER_CODE,
	PARTNER_NAME,
	TARIFF_CODE,
	TARIFF_DESC,
	ICCID,
	PAYM_HANDSET_PARTNER_CODE,
	PAYM_TARIFF_MRC_PARTNER_CODE,
	PAYM_TARIFF_CODE,
	PAYM_PRODUCT_CODE,
	PAYM_TENURE,
	PAYG_PARTNER_CODE,
	PAYG_PRODUCT_CODE,
	BAN,
	PRICE_MODIFIER,
	DEVICE_DESC,
	DEVICE_ID,
	DISCONNECT_REASON,
	DISCONNECT_DATE,
	TENURE,
	-- CREDIT_TYPE,
	PERIOD,
	INSERT_TS
)
SELECT DISTINCT
	TLR.COMPENSATION_DATE									AS COMPENSATION_DATE,
	TLR.ACCOUNTING_DATE										AS ACCOUNTING_DATE,
	TLR.ORDER_ID											AS ORDER_ID,
	TLR.LINE_NUMBER											AS LINE_NUMBER,
	TLR.SUBLINE_NUMBER										AS SUBLINE_NUMBER,
	TLR.DATA_SOURCE											AS SOURCE,
	TLR.GENERIC_ATTRIBUTE_5									AS EQUIPMENT_SOURCED,
	TLR.EVENT_TYPE_ID										AS EVENT_TYPE,
	TLR.GENERIC_ATTRIBUTE_23								AS CONTRACT_TYPE,
	TLR.GENERIC_ATTRIBUTE_24								AS COMMITMENT_TYPE,
	TLR.GENERIC_ATTRIBUTE_22								AS SERVICE_TYPE,
	TLR.CHANNEL												AS CHANNEL,
	CASE
		WHEN UPPER(TLR.EVENT_TYPE_ID) IN ('ET_PAYG_NONITU', 'ET_PAYG_ITU_SHIPMENT', 'ET_PAYG_NONITU_SHIPMENT') THEN 'LT_MCAL_PAYG_Pricebook'
		WHEN UPPER(TLR.GENERIC_ATTRIBUTE_22) = 'VOICE' AND UPPER(TLR.GENERIC_ATTRIBUTE_23) = 'DEVICE' AND (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR' OR (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR_BACK' AND TLR.GENERIC_DATE_6 IS NOT NULL))
		THEN CASE
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'NEW CONTRACT' THEN 'LT_MCAL_CVHA_HandsetBonus_NEW'
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'UPGRADE' THEN 'LT_MCAL_CVHA_HandsetBonus_UPG'
			END
		WHEN UPPER(TLR.GENERIC_ATTRIBUTE_22) = 'VOICE' AND UPPER(TLR.GENERIC_ATTRIBUTE_23) = 'SIMO' AND (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR' OR (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR_BACK' AND TLR.GENERIC_DATE_6 IS NOT NULL))
		THEN CASE
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'NEW CONTRACT' THEN 'LT_MCAL_CVSA_NEW'
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'UPGRADE' THEN 'LT_MCAL_CVSA_UPG'
			END
		WHEN UPPER(TLR.GENERIC_ATTRIBUTE_22) = 'MBB' AND UPPER(TLR.GENERIC_ATTRIBUTE_23) = 'DEVICE' AND (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR' OR UPPER(TLR.EVENT_TYPE_ID) = 'ET_BILL_INVO' OR (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR_BACK' AND TLR.GENERIC_DATE_6 IS NOT NULL))
		THEN CASE
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'NEW CONTRACT' THEN 'LT_MCAL_CMHA_NEW'
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'UPGRADE' THEN 'LT_MCAL_CMHU_UPG'
			END
		WHEN UPPER(TLR.GENERIC_ATTRIBUTE_22) = 'MBB' AND UPPER(TLR.GENERIC_ATTRIBUTE_23) = 'SIMO' AND (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR' OR UPPER(TLR.EVENT_TYPE_ID) = 'ET_BILL_INVO' OR (UPPER(TLR.EVENT_TYPE_ID) = 'ET_CONN_UPFR_BACK' AND TLR.GENERIC_DATE_6 IS NOT NULL))
		THEN CASE
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'NEW CONTRACT' THEN 'LT_MCAL_CMSA_NEW'
				WHEN UPPER(TLR.GENERIC_ATTRIBUTE_24) = 'UPGRADE' THEN 'LT_MCAL_CMSU_UPG'
			END
	END AS LOOKUP_NAME,
	TLR.EXTENDED_ATTRIBUTE_4								AS IMEI1,
	TLR.EXTENDED_ATTRIBUTE_5								AS IMEI2,
	TLR.EXTENDED_ATTRIBUTE_6								AS INITIAL_MSISDN,
	NULL													AS PORTIN_MSISDN,
	TLR.GENERIC_ATTRIBUTE_20								AS PARTNER_CODE,
	CP.LASTNAME												AS PARTNER_NAME,
	TLR.GENERIC_ATTRIBUTE_1									AS TARIFF_CODE,
	TLR.GENERIC_ATTRIBUTE_2									AS TARIFF_DESC,
	TLR.EXTENDED_ATTRIBUTE_3								AS ICCID,

	--PAYM_HANDSET_PARTNER_CODE
	CASE
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVHA_HandsetBonus_NEW', 'LT_MCAL_CVHA_HandsetBonus_UPG')
		THEN CASE WHEN PBK_HS.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMHA_NEW', 'LT_MCAL_CMHU_UPG')
		THEN CASE WHEN PBK_CMHA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		ELSE 'N/A'
	END AS PAYM_HANDSET_PARTNER_CODE,

	--PAYM_TARIFF_MRC_PARTNER_CODE
	CASE
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVHA_MRC_TariffBonus_NEW', 'LT_MCAL_CVHA_MRC_TariffBonus_UPG')
		THEN CASE WHEN PBK_MRC.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVSA_NEW', 'LT_MCAL_CVSA_UPG')
		THEN CASE WHEN PBK_CVSA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMHA_NEW', 'LT_MCAL_CMHU_UPG')
		THEN CASE WHEN PBK_CMHA_TARIFF.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMSA_NEW', 'LT_MCAL_CMSU_UPG')
		THEN CASE WHEN PBK_CMSA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		ELSE 'N/A'
	END AS PAYM_TARIFF_MRC_PARTNER_CODE,

	--PAYM_TARIFF_CODE
	CASE
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVHA_HandsetBonus_NEW', 'LT_MCAL_CVHA_HandsetBonus_UPG')
		THEN CASE WHEN PBK_HS.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVHA_MRC_TariffBonus_NEW', 'LT_MCAL_CVHA_MRC_TariffBonus_UPG')
		THEN CASE WHEN PBK_MRC.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVSA_NEW', 'LT_MCAL_CVSA_UPG')
		THEN CASE WHEN PBK_CVSA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMHA_NEW', 'LT_MCAL_CMHU_UPG')
		THEN CASE WHEN PBK_CMHA_TARIFF.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMSA_NEW', 'LT_MCAL_CMSU_UPG')
		THEN CASE WHEN PBK_CMSA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END	
		ELSE 'N/A'
	END AS PAYM_TARIFF_CODE,

	--PAYM_PRODUCT_CODE
	CASE
		WHEN LOOKUP_NAME IN('LT_MCAL_CVHA_HandsetBonus_NEW', 'LT_MCAL_CVHA_HandsetBonus_UPG')
		THEN CASE WHEN PBK_HS.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		ELSE 'N/A'
	END AS PAYM_PRODUCT_CODE,

	--PAYM_TENURE
	CASE
		WHEN LOOKUP_NAME IN ('LT_MCAL_CVHA_MRC_TariffBonus_NEW', 'LT_MCAL_CVHA_MRC_TariffBonus_UPG')
		THEN CASE WHEN PBK_MRC.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END 
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMHA_NEW', 'LT_MCAL_CMHU_UPG')
		THEN CASE WHEN PBK_CMHA_TARIFF.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END 
		WHEN LOOKUP_NAME IN ('LT_MCAL_CMSA_NEW', 'LT_MCAL_CMSU_UPG')
		THEN CASE WHEN PBK_CMSA.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END 
		ELSE 'N/A'
	END AS PAYM_TENURE,

	--PAYG
	CASE
		WHEN LOOKUP_NAME='LT_MCAL_PAYG_Pricebook'
		THEN CASE WHEN PBK_PAYG.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		ELSE 'N/A'
	END AS PAYG_PARTNER_CODE,

	CASE
		WHEN LOOKUP_NAME='LT_MCAL_PAYG_Pricebook'
		THEN CASE WHEN PBK_PAYG.MDLT_NAME IS NOT NULL THEN 'N' ELSE 'Y' END
		ELSE 'N/A'
	END AS PAYG_PRODUCT_CODE,

	TLR.BILL_TO_CUST_ID																AS BAN,
	TLR.GENERIC_NUMBER_6															AS PRICE_MODIFIER,
	TLR.GENERIC_ATTRIBUTE_10														AS DEVICE_DESC,
	TLR.GENERIC_ATTRIBUTE_9															AS DEVICE_ID,
	NVL(TLR.GENERIC_ATTRIBUTE_5,'') || ' - ' || NVL(TLR.GENERIC_ATTRIBUTE_4,'')		AS DISCONNECT_REASON,
	TLR.GENERIC_DATE_6																AS DISCONNECT_DATE,
	TLR.GENERIC_NUMBER_1															AS TENURE,
	-- TLR.CREDIT_TYPE																	AS CREDIT_TYPE,
	TLR.PERIOD																		AS PERIOD,
	CURRENT_TIMESTAMP																AS INSERT_TS

FROM ATO_CEG_STG.SALES_TRANSACTION TLR

INNER JOIN(
	SELECT * FROM ATO_CEG_STG.CS_EVENTTYPE
	QUALIFY ROW_NUMBER() OVER(PARTITION BY EVENTTYPEID ORDER BY REMOVEDATE DESC) = 1
) EVENTTYPE
ON TLR.EVENT_TYPE_ID = EVENTTYPE.EVENTTYPEID

LEFT JOIN(
	SELECT * FROM ATO_CEG_STG.CS_PARTICIPANT
	QUALIFY ROW_NUMBER() OVER(PARTITION BY GENERICATTRIBUTE12 ORDER BY REMOVEDATE DESC) = 1
) CP
ON 'IP_' || CP.GENERICATTRIBUTE12 = TLR.GENERIC_ATTRIBUTE_20

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_HS
ON PBK_HS.MDLT_NAME = LOOKUP_NAME
AND PBK_HS.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_HS.PRODUCT_CODE = TLR.GENERIC_ATTRIBUTE_9
AND PBK_HS.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_HS.SOURCE_ATTR = TLR.GENERIC_ATTRIBUTE_6
AND PBK_HS.REWARD_TYPE = CASE
							WHEN UPPER(TLR.GENERIC_ATTRIBUTE_6) = 'THREE' THEN 'three_source'
							ELSE 'o_source'
						 END
AND PBK_HS.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_HS.EFFECTIVE_START_DT AND PBK_HS.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_MRC
ON PBK_MRC.MDLT_NAME = LOOKUP_NAME
AND PBK_MRC.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_MRC.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_MRC.REWARD_TYPE = 'MRC Share'
AND PBK_MRC.TENURE = TLR.GENERIC_NUMBER_1
AND PBK_MRC.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_MRC.EFFECTIVE_START_DT AND PBK_MRC.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_CVSA
ON PBK_CVSA.MDLT_NAME = LOOKUP_NAME
AND PBK_CVSA.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_CVSA.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_CVSA.REWARD_TYPE = 'Tariff'
AND PBK_CVSA.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_CVSA.EFFECTIVE_START_DT AND PBK_CVSA.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_CMHA
ON PBK_CMHA.MDLT_NAME = LOOKUP_NAME
AND PBK_CMHA.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_CMHA.PRODUCT_CODE = TLR.GENERIC_ATTRIBUTE_9
AND PBK_CMHA.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_CMHA.TENURE = TLR.GENERIC_NUMBER_1
AND PBK_CMHA.REWARD_TYPE = 'Device'
AND PBK_CMHA.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_CMHA.EFFECTIVE_START_DT AND PBK_CMHA.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_CMHA_TARIFF
ON PBK_CMHA_TARIFF.MDLT_NAME = LOOKUP_NAME
AND PBK_CMHA_TARIFF.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_CMHA_TARIFF.PRODUCT_CODE = TLR.GENERIC_ATTRIBUTE_9
AND PBK_CMHA_TARIFF.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_CMHA_TARIFF.TENURE = TLR.GENERIC_NUMBER_1
AND PBK_CMHA_TARIFF.REWARD_TYPE = 'Tariff'
AND PBK_CMHA_TARIFF.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_CMHA_TARIFF.EFFECTIVE_START_DT AND PBK_CMHA_TARIFF.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_CMSA
ON PBK_CMSA.MDLT_NAME = LOOKUP_NAME
AND PBK_CMSA.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_CMSA.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_CMSA.TENURE = TLR.GENERIC_NUMBER_1
AND PBK_CMSA.REWARD_TYPE = 'Tariff'
AND PBK_CMSA.COMMITMENT_TYPE = TLR.GENERIC_ATTRIBUTE_24
AND TLR.ACCOUNTING_DATE BETWEEN PBK_CMSA.EFFECTIVE_START_DT AND PBK_CMSA.EFFECTIVE_END_DT - 1

LEFT JOIN ATO_CEG_STG.TBL_PRS_PRICEBOOK_COMMISSIONS PBK_PAYG
ON PBK_PAYG.MDLT_NAME = LOOKUP_NAME
AND PBK_PAYG.TARIFF_CODE = TLR.GENERIC_ATTRIBUTE_1
AND PBK_PAYG.PARTNER_CODE = TLR.GENERIC_ATTRIBUTE_20
AND PBK_PAYG.REWARD_TYPE = 'ITU Y/N'
AND PBK_PAYG.VALUE =  CASE
						WHEN TLR.EVENT_TYPE_ID = 'ET_PAYG_ITU_SHIPMENT' THEN 1
						WHEN TLR.EVENT_TYPE_ID IN ('ET_PAYG_NONITU','ET_PAYG_NONITU_SHIPMENT') THEN 0
					END
AND TLR.COMPENSATION_DATE BETWEEN PBK_PAYG.EFFECTIVE_START_DT AND PBK_PAYG.EFFECTIVE_END_DT - 1
;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()