# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.TBL_CALLIDUS_THREEUK_COMMISSIONS_CREDITS
(
PAYMENTRUNNUMBER
,PARTICIPANTID
,PARTICIPANTARCUSTOMERNUMBER
,PARTICIPANTAPSUPPLIERNUMBER
,PARTICIPANTNAME
,PARTICIPANTVATSTATUS
,PARTICIPANTVATNUMBER
,DOCNUMBER
,DOCDATE
,DOCTYPE
,DOCLINETYPE
,DOCLINETEXT
,CALLIDUSORDERNUMBER
,CALLIDUSORDERLINENUMBER
,CALLIDUSORDERSUBLINENUMBER
,CALLIDUSEVENTTYPE
,CALLIDUSCOMPENSATIONDATE
,CREDITTYPE
,EARNINGSGROUP
,PAYMENTVALUEEXVAT
,PAYMENTORCLAWBACK
,INSERT_TS
)
SELECT
CTCC.PAYMENT_RUN_NUMBER,
CTCC.PARTICIPANT_ID,
CTCC.PARTICIPANT_AR_CUSTOMER_NUMBER,
CTCC.PARTICIPANT_AP_SUPPLIER_NUMBER,
CTCC.PARTICIPANT_NAME,
CTCC.PARTICIPANT_VAT_STATUS,
CTCC.PARTICIPANT_VAT_NUMBER,
CTCC.DOC_NUMBER,
CTCC.DOC_DATE,
CTCC.DOC_TYPE,
CTCC.DOC_LINE_TYPE,
CTCC.DOC_LINE_TEXT,
CTCC.CALLIDUS_ORDER_NUMBER,
CTCC.CALLIDUS_ORDER_LINE_NUMBER,
CTCC.CALLIDUS_ORDER_SUBLINE_NUMBER,
CTCC.CALLIDUS_EVENTTYPE,
CTCC.CALLIDUS_COMPENSATION_DATE,
CTCC.CREDITTYPE,
CTCC.EARNINGS_GROUP,
CTCC.PAYMENT_VALUE_EXVAT,
CTCC.PAYMENT_OR_CLAWBACK,
CURRENT_TIMESTAMP() AS INSERT_TS

FROM {sfDatabase}.ATO_CEG_STG.CALLIDUS_THREEUK_COMM_CREDITS CTCC;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

cs.close()
conn.close()