# Databricks notebook source
# MAGIC %md
# MAGIC # Callidus AP Commission Payment Extract
# MAGIC
# MAGIC Loads extract data into `SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT_FILE` and generates
# MAGIC the outbound `.dat` file:
# MAGIC - File name: `AP_COMMISSION_PAYMENTS_<PAYMENT_RUN_NUMBER>.dat`
# MAGIC - Delimiter: `~`
# MAGIC - No quotes
# MAGIC - Path: `mft-out/aldm/outbound/Callidus`

# COMMAND ----------

# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/transformer/aldm_callidus/nb-Callidus_functions"

# COMMAND ----------

import csv
import os

import pandas as pd
import snowflake.connector

# Adjust if your workspace uses a different mount/volume for MFT outbound
OUTPUT_DIR = "/Volumes/SIT_aldm/aldm_oper/mft-out/aldm/outbound_1/AP_COMMISSION_PAYMENTS"

sf_Options_py = {
    "user": f"{sfUser}",
    "private_key": f"{pem_private_key}",
    "account":"THREEMOBILE.west-europe.azure",
    "database": f"{sfDatabase}",
    "warehouse": f"{sfWarehouse}",
    "schema": f"{sfNondoxTgtSchema}",
    "disable_ocsp_checks": "True",
}

conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

files = dbutils.jobs.taskValues.get(
    taskKey="EMAIL_INGEST", key="in_execution", default=[], debugValue= []
)
for f in files:
    source_file = f["source_file"]
    period      = f["period"]
    Sequence    = f["sequence"]

print(f"period - {period}  Sequence - {Sequence}  source_file - {source_file}")
# period = 'JULY 2026 M' for manual run or testing

# COMMAND ----------

query = f"""INSERT INTO SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT
(
    USERID,
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    EARNINGGROUPID,
    INVOICE_NO,
    INVOICE_TYPE_LOOKUP_CODE,
    INVOICE_DATE,
    VENDOR_NUMBER,
    VENDOR_NAME,
    VENDOR_SITE_CODE,
    INVOICE_AMOUNT,
    INVOICE_CURRENCY_CODE,
    SOURCE,
    PAY_RUN_NUMBER,
    LINE_NUMBER,
    LINETYPE_LOOKUP_CODE,
    LINE_AMOUNT,
    EARNINGGROUP_DESC,
    TAXCODE,
    DISC_CODE_CONCATENATED,
    VAT_LOCATION,
    VAT_CODE,
    VAT_RATE,
    VAT_REG_NUMBER,
    ACCOUNT_PAY_REF,
    ACCOUNT_RECV_REF,
    MODIFIED_DATE,
    INSERT_TS,
    UPDATE_TS
)
SELECT
    USERID,
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    EARNINGGROUPID,
    INVOICE_NO,
    INVOICE_TYPE_LOOKUP_CODE,
    INVOICE_DATE,
    VENDOR_NUMBER,
    VENDOR_NAME,
    VENDOR_SITE_CODE,
    INVOICE_AMOUNT,
    INVOICE_CURRENCY_CODE,
    SOURCE,
    PAY_RUN_NUMBER,
    LINE_NUMBER,
    LINETYPE_LOOKUP_CODE,
    LINE_AMOUNT,
    EARNINGGROUP_DESC,
    TAXCODE,
    DISC_CODE_CONCATENATED,
    VAT_LOCATION,
    VAT_CODE,
    VAT_RATE,
    VAT_REG_NUMBER,
    ACCOUNT_PAY_REF,
    ACCOUNT_RECV_REF,
    MODIFIED_DATE,
    CURRENT_TIMESTAMP() AS INSERT_TS,
    CURRENT_TIMESTAMP() AS UPDATE_TS
FROM
(
---------------------------------dataset 1---------------------------------------------
SELECT
    PARTY.USERID AS USERID,
    DEP.PERIOD AS PERIOD_NAME,
    PER.STARTDATE AS PERIOD_START_DATE,
    DATEADD(DAY, -1, PER.ENDDATE) AS PERIOD_END_DATE,
    DEP.EARNING_GROUPS AS EARNINGGROUPID,
    PARTY.GENERICATTRIBUTE12 || TO_CHAR(CURRENT_DATE(), 'DDMMYY') AS INVOICE_NO,
    NULL AS INVOICE_TYPE_LOOKUP_CODE,
    CURRENT_DATE() AS INVOICE_DATE,
    PARTY.GENERICATTRIBUTE9 AS VENDOR_NUMBER,
    TRIM(PARTY.FIRSTNAME) || TRIM(PARTY.LASTNAME) AS VENDOR_NAME, ----need to confirm with vivek
    'COMMISSIONS' AS VENDOR_SITE_CODE,
    SUM(DEP.DEPOSIT_AMOUNT) OVER (
        PARTITION BY DEP.PERIOD, DEP.PARTNER_CODE
        ORDER BY DEP.PERIOD, DEP.PARTNER_CODE
    ) AS INVOICE_AMOUNT,
    'GBP' AS INVOICE_CURRENCY_CODE,
    'H3G Commissions_' || DEP.PERIOD AS SOURCE,
    NULL AS PAY_RUN_NUMBER,
    DENSE_RANK() OVER (
        PARTITION BY DEP.PARTNER_CODE
        ORDER BY DEP.PARTNER_CODE, DEP.EARNING_GROUPS
    ) AS LINE_NUMBER,
    'ITEM' AS LINETYPE_LOOKUP_CODE,
    DEP.DEPOSIT_AMOUNT AS LINE_AMOUNT,
    DEP.GA1_LINE_TYPE_DESC AS EARNINGGROUP_DESC,
    'Standard' AS TAXCODE,
    GL_STRING.GENERICATTRIBUTE4 AS DISC_CODE_CONCATENATED,
    PARTY.GENERICATTRIBUTE7 AS VAT_LOCATION,
    VAT_RATES.GENERICNUMBER2 AS VAT_CODE,
    VAT_RATES.VAT_RATE AS VAT_RATE,
    PARTY.GENERICATTRIBUTE6 AS VAT_REG_NUMBER,
    PARTY.GENERICATTRIBUTE9 AS ACCOUNT_PAY_REF, ----need to confirm with vivek
    PARTY.GENERICATTRIBUTE11 AS ACCOUNT_RECV_REF,
    CURRENT_DATE() AS MODIFIED_DATE
FROM
(
    SELECT * FROM SIT_IDW.ATO_CEG_STG.TBL_FACT_PAYM_DEPOSITS
    -- WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -4, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    WHERE PERIOD = '{period}'
    UNION
    SELECT * FROM SIT_IDW.ATO_CEG_STG.TBL_FACT_PAYG_DEPOSITS
    -- WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -4, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    WHERE PERIOD = '{period}'
) DEP
INNER JOIN (
    SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_PARTICIPANT 
    WHERE GENERICATTRIBUTE7 IS NOT NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY GENERICATTRIBUTE12 ORDER BY REMOVEDATE DESC) = 1 ---need to confirm with vivek
) PARTY
ON DEP.PARTNER_CODE = 'IP_'||PARTY.GENERICATTRIBUTE12


INNER JOIN(
    SELECT
        C.GENERICATTRIBUTE1,
        C.GENERICATTRIBUTE4,
        C.GENERICNUMBER2
    FROM
    (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_GENERICCLASSIFIER C
        QUALIFY ROW_NUMBER() OVER(PARTITION BY C.GENERICATTRIBUTE1 ORDER BY C.REMOVEDATE DESC) = 1
    ) C
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORY_CLASSIFIERS B
        QUALIFY ROW_NUMBER() OVER (PARTITION BY B.CLASSIFIERSEQ ORDER BY B.REMOVEDATE DESC) = 1
    ) B
    ON C.CLASSIFIERSEQ = B.CLASSIFIERSEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORYTREE A
        WHERE TRIM(UPPER(A.NAME)) = 'GL STRINGS'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY A.CATEGORYTREESEQ ORDER BY A.REMOVEDATE DESC) = 1
    ) A
    ON B.CATEGORYTREESEQ = A.CATEGORYTREESEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CLASSIFIER D
        QUALIFY ROW_NUMBER() OVER (PARTITION BY D.CLASSIFIERSEQ ORDER BY D.REMOVEDATE DESC) = 1
    ) D
    ON B.CLASSIFIERSEQ = D.CLASSIFIERSEQ

) GL_STRING
ON DEP.EARNING_GROUPS = GL_STRING.GENERICATTRIBUTE1
LEFT JOIN
(
    SELECT
        C.GENERICATTRIBUTE1,
        C.GENERICNUMBER2,
        C.GENERICNUMBER1 AS VAT_RATE
    FROM
    (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_GENERICCLASSIFIER C
        QUALIFY ROW_NUMBER() OVER(PARTITION BY C.GENERICATTRIBUTE1 ORDER BY C.REMOVEDATE DESC) = 1
    ) C
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORY_CLASSIFIERS B
        QUALIFY ROW_NUMBER() OVER (PARTITION BY B.CLASSIFIERSEQ ORDER BY B.REMOVEDATE DESC) = 1
    ) B
    ON C.CLASSIFIERSEQ = B.CLASSIFIERSEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORYTREE A
        WHERE TRIM(UPPER(A.NAME)) = 'LOCATION'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY A.CATEGORYTREESEQ ORDER BY A.REMOVEDATE DESC) = 1
    ) A
    ON B.CATEGORYTREESEQ = A.CATEGORYTREESEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CLASSIFIER D
        QUALIFY ROW_NUMBER() OVER (PARTITION BY D.CLASSIFIERSEQ ORDER BY D.REMOVEDATE DESC) = 1
    ) D
    ON B.CLASSIFIERSEQ = D.CLASSIFIERSEQ
) VAT_RATES
ON PARTY.GENERICATTRIBUTE7 = VAT_RATES.GENERICATTRIBUTE1
AND GL_STRING.GENERICNUMBER2 = VAT_RATES.GENERICNUMBER2

LEFT JOIN (
    SELECT
        NAME,
        STARTDATE,
        ENDDATE
    FROM SIT_IDW.ATO_CEG_STG.CS_PERIOD
    QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY REMOVEDATE DESC) = 1
) PER
ON DEP.PERIOD = PER.NAME

UNION ALL
---------------------------------dataset 2---------------------------------------------
SELECT
    PARTY.USERID AS USERID,
    DEP.PERIOD AS PERIOD_NAME,
    PER.STARTDATE AS PERIOD_START_DATE,
    DATEADD(DAY, -1, PER.ENDDATE) AS PERIOD_END_DATE,
    DEP.EARNING_GROUPS AS EARNINGGROUPID,
    PARTY.GENERICATTRIBUTE12 || TO_CHAR(CURRENT_DATE(), 'DDMMYY') AS INVOICE_NO,
    NULL AS INVOICE_TYPE_LOOKUP_CODE,
    CURRENT_DATE() AS INVOICE_DATE,
    PARTY.GENERICATTRIBUTE9 AS VENDOR_NUMBER,
    TRIM(PARTY.FIRSTNAME) || TRIM(PARTY.LASTNAME) AS VENDOR_NAME, ----need to confirm with vivek
    'COMMISSIONS' AS VENDOR_SITE_CODE,
    SUM(DEP.DEPOSIT_AMOUNT) OVER (
        PARTITION BY DEP.PERIOD, DEP.PARTNER_CODE
        ORDER BY DEP.PERIOD, DEP.PARTNER_CODE
    ) AS INVOICE_AMOUNT,
    'GBP' AS INVOICE_CURRENCY_CODE,
    'H3G Commissions_' || DEP.PERIOD AS SOURCE,
    NULL AS PAY_RUN_NUMBER,
    DENSE_RANK() OVER (
        PARTITION BY DEP.PARTNER_CODE
        ORDER BY DEP.PARTNER_CODE, DEP.EARNING_GROUPS
    ) AS LINE_NUMBER,
    'ITEM' AS LINETYPE_LOOKUP_CODE,
    DEP.DEPOSIT_AMOUNT AS LINE_AMOUNT,
    DEP.GA1_LINE_TYPE_DESC AS EARNINGGROUP_DESC,
    'Standard' AS TAXCODE,
    GL_STRING.GENERICATTRIBUTE4 AS DISC_CODE_CONCATENATED,
    PARTY.GENERICATTRIBUTE7 AS VAT_LOCATION,
    NULL AS VAT_CODE,
    NULL AS VAT_RATE,
    PARTY.GENERICATTRIBUTE6 AS VAT_REG_NUMBER,
    PARTY.GENERICATTRIBUTE9 AS ACCOUNT_PAY_REF, ----need to confirm with vivek
    PARTY.GENERICATTRIBUTE11 AS ACCOUNT_RECV_REF,
    CURRENT_DATE() AS MODIFIED_DATE
FROM
(
    SELECT * FROM SIT_IDW.ATO_CEG_STG.TBL_FACT_PAYM_DEPOSITS
    -- WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -4, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    WHERE PERIOD = '{period}'
    UNION
    SELECT * FROM SIT_IDW.ATO_CEG_STG.TBL_FACT_PAYG_DEPOSITS
    -- WHERE PERIOD = TO_VARCHAR(DATEADD(MONTH, -4, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
    WHERE PERIOD = '{period}'
) DEP

INNER JOIN (
    SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_PARTICIPANT 
    WHERE GENERICATTRIBUTE7 IS NULL
    QUALIFY ROW_NUMBER() OVER(PARTITION BY GENERICATTRIBUTE12 ORDER BY REMOVEDATE DESC) = 1 ---need to confirm with vivek
) PARTY
ON DEP.PARTNER_CODE = 'IP_'||PARTY.GENERICATTRIBUTE12

LEFT JOIN( ----------to be confirm from vivek
    SELECT
        C.GENERICATTRIBUTE1,
        C.GENERICATTRIBUTE4,
        C.GENERICNUMBER2
    FROM
    (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_GENERICCLASSIFIER C
        QUALIFY ROW_NUMBER() OVER(PARTITION BY C.GENERICATTRIBUTE1 ORDER BY C.REMOVEDATE DESC) = 1
    ) C
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORY_CLASSIFIERS B
        QUALIFY ROW_NUMBER() OVER (PARTITION BY B.CLASSIFIERSEQ ORDER BY B.REMOVEDATE DESC) = 1
    ) B
    ON C.CLASSIFIERSEQ = B.CLASSIFIERSEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CATEGORYTREE A
        WHERE TRIM(UPPER(A.NAME)) = 'GL STRINGS'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY A.CATEGORYTREESEQ ORDER BY A.REMOVEDATE DESC) = 1
    ) A
    ON B.CATEGORYTREESEQ = A.CATEGORYTREESEQ
    INNER JOIN (
        SELECT * FROM SIT_IDW.ATO_CEG_STG.CS_CLASSIFIER D
        QUALIFY ROW_NUMBER() OVER (PARTITION BY D.CLASSIFIERSEQ ORDER BY D.REMOVEDATE DESC) = 1
    ) D
    ON B.CLASSIFIERSEQ = D.CLASSIFIERSEQ

) GL_STRING
ON DEP.EARNING_GROUPS = GL_STRING.GENERICATTRIBUTE1

LEFT JOIN (
    SELECT
        NAME,
        STARTDATE,
        ENDDATE
    FROM SIT_IDW.ATO_CEG_STG.CS_PERIOD
    QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY REMOVEDATE DESC) = 1
) PER
ON DEP.PERIOD = PER.NAME
)
;

"""

cs.execute(query)
print(f"Rows inserted into AP_COMMISSION_PAYMENT_FILE: {cs.rowcount}")

# COMMAND ----------

extract_query = f"""
INSERT INTO SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT_FILE
(
    INVOICE_NO,
    INVOICE_TYPE_LOOKUP_CODE,
    INVOICE_DATE,
    PO_HEADER_ID,
    PO_NUMBER_ID,
    VENDOR_NUMBER,
    VENDOR_NAME,
    VENDOR_SITE_CODE,
    INVOICE_AMOUNT,
    INVOICE_CURRENCY_CODE,
    SOURCE,
    PAYMENT_RUN_NUMBER,
    LINE_NUMBER,
    LINE_TYPE_LOOKUP_CODE,
    LINE_AMOUNT,
    DESCRIPTION,
    TAX_CODE,
    DIST_CODE_CONCATENATED,
    FILE_NAME,
    EXTRACT_RUN_DATE
)
WITH RUN AS (
    SELECT LPAD(
        TO_VARCHAR(
            COALESCE(
                (
                    SELECT MAX(TRY_TO_NUMBER(TO_VARCHAR(PAYMENT_RUN_NUMBER)))
                    FROM SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT_FILE
                ),
                0
            ) + 1
        ),
        6,
        '0'
    ) AS PAYMENT_RUN_NUMBER
)
SELECT
    INVOICE_NO,
    CASE
        WHEN INVOICE_AMOUNT > 0 THEN 'Standard'
        ELSE 'Credit'
    END AS INVOICE_TYPE_LOOKUP_CODE,
    INVOICE_DATE,
    NULL AS PO_HEADER_ID,
    NULL AS PO_NUMBER_ID,
    VENDOR_NUMBER,
    VENDOR_NAME,
    VENDOR_SITE_CODE,
    ROUND(INVOICE_AMOUNT, 2) AS INVOICE_AMOUNT,
    'GBP' AS INVOICE_CURRENCY_CODE,
    SOURCE,
    RUN.PAYMENT_RUN_NUMBER AS PAYMENT_RUN_NUMBER,
    LINE_NUMBER,
    LINETYPE_LOOKUP_CODE AS LINE_TYPE_LOOKUP_CODE,
    SUM(LINE_AMOUNT) AS LINE_AMOUNT,
    EARNINGGROUP_DESC AS DESCRIPTION,
    TAXCODE AS TAX_CODE,
    DISC_CODE_CONCATENATED AS DIST_CODE_CONCATENATED,
    'AP_COMMISSION_PAYMENTS_' || RUN.PAYMENT_RUN_NUMBER || '.dat' AS FILE_NAME,
    CURRENT_TIMESTAMP() AS EXTRACT_RUN_DATE
FROM SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT
CROSS JOIN RUN
-- WHERE PERIOD_NAME = TO_VARCHAR(DATEADD(MONTH, -4, DATE_TRUNC('MONTH', CURRENT_DATE)), 'MMMM YYYY') || ' M'
WHERE PERIOD_NAME = '{period}'
GROUP BY USERID, PERIOD_NAME, PERIOD_START_DATE, PERIOD_END_DATE, EARNINGGROUPID, INVOICE_NO, INVOICE_DATE, VENDOR_NUMBER,
    VENDOR_NAME, VENDOR_SITE_CODE, INVOICE_AMOUNT, INVOICE_CURRENCY_CODE, SOURCE, LINE_NUMBER, LINETYPE_LOOKUP_CODE, EARNINGGROUP_DESC,
    TAXCODE, DISC_CODE_CONCATENATED, VAT_LOCATION, VAT_CODE, VAT_RATE, VAT_REG_NUMBER, ACCOUNT_PAY_REF, ACCOUNT_RECV_REF, MODIFIED_DATE,
    RUN.PAYMENT_RUN_NUMBER
"""

cs.execute(extract_query)
print(f"Rows inserted into AP_COMMISSION_PAYMENT_FILE: {cs.rowcount}")

# COMMAND ----------

metadata_query = """
SELECT PAYMENT_RUN_NUMBER, FILE_NAME
FROM SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT_FILE
QUALIFY ROW_NUMBER() OVER (ORDER BY EXTRACT_RUN_DATE DESC) = 1
"""

cs.execute(metadata_query)
payment_run_number, file_name = cs.fetchone()
print(f"Payment run number: {payment_run_number}")
print(f"Output file name: {file_name}")

# COMMAND ----------

file_query = """
SELECT
    INVOICE_NO,
    INVOICE_TYPE_LOOKUP_CODE,
    INVOICE_DATE,
    PO_HEADER_ID,
    PO_NUMBER_ID,
    VENDOR_NUMBER,
    VENDOR_NAME,
    VENDOR_SITE_CODE,
    INVOICE_AMOUNT,
    INVOICE_CURRENCY_CODE,
    SOURCE,
    PAYMENT_RUN_NUMBER,
    LINE_NUMBER,
    LINE_TYPE_LOOKUP_CODE,
    LINE_AMOUNT,
    DESCRIPTION,
    TAX_CODE,
    DIST_CODE_CONCATENATED
FROM SIT_IDW.PRS_CEG_EXT.AP_COMMISSION_PAYMENT_FILE
WHERE PAYMENT_RUN_NUMBER = %s
--ORDER BY INVOICE_NO, LINE_NUMBER
"""

cs.execute(file_query, (payment_run_number,))
rows = cs.fetchall()
columns = [col[0] for col in cs.description]

if not rows:
    import sys
    dbutils.notebook.exit(f"No extract rows found for PAYMENT_RUN_NUMBER={payment_run_number}")

df = pd.DataFrame(rows, columns=columns)
df = df.fillna("")

# COMMAND ----------

os.makedirs(OUTPUT_DIR, exist_ok=True)
output_path = os.path.join(OUTPUT_DIR, file_name)

df.to_csv(
    output_path,
    sep="~",
    index=False,
    header=False,
    quoting=csv.QUOTE_NONE,
    escapechar="\\",
    na_rep="",
)

print(f"Extract file generated: {output_path}")
print(f"Record count: {len(df)}")

# COMMAND ----------

cs.close()
conn.close()

# COMMAND ----------

# DBTITLE 1,Install azure-storage-file-share
# MAGIC %pip install --upgrade azure-storage-file-share

# COMMAND ----------

import importlib
importlib.invalidate_caches()
from azure.storage.fileshare import ShareFileClient, ShareDirectoryClient
# from azure.storage.fileshare import ShareDirectoryClient

if os.path.isfile(output_path):
    # file is present at output_path location
    # Archive old files in Azure File Share
    print("Archiving old files in Azure File Share...")
    archive_files_at_azure_share(fs_conn_str, fs_name, "callidus/AP_COMMISSION_PAYMENTS", "AP_COMMISSION_PAYMENTS")
    print("Old files archived successfully.")

    # Move new file to Azure File Share
    print("Uploading new file to Azure File Share...")
    move_files_to_azure_share(fs_conn_str, fs_name, f"{mft_out}/aldm/outbound_1/AP_COMMISSION_PAYMENTS", "callidus/AP_COMMISSION_PAYMENTS", "AP_COMMISSION_PAYMENTS")
    print("New file uploaded successfully.")
else:
    # file is not present at output_path location
    print(f"File not found at {output_path}. No upload or archive performed.")