# Databricks notebook source
# MAGIC %run "/Workspace/Repos/Aldm Repository/ALDM/databricks/config/config"

# COMMAND ----------

import snowflake.connector
sf_Options_py = {
  "user":f"{sfUser}",
  "private_key":f"{pem_private_key}",
  "account":"THREEMOBILE.west-europe.azure",
  "database":f"{sfDatabase}",
  "warehouse":f"{sfWarehouse}",
  "schema": f"{sfNondoxTgtSchema}",
  "disable_ocsp_checks":"True"
}
conn = snowflake.connector.connect(**sf_Options_py)
cs = conn.cursor()

# COMMAND ----------

period_name_value = dbutils.widgets.get("PERIOD_NAME")
print(period_name_value)

# COMMAND ----------

query = f"""

DELETE FROM {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_SUMMARY
--WHERE PERIOD_NAME = TRIM(TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'MMMM YYYY')) || ' M'
WHERE PERIOD_NAME = '{period_name_value}'
;
"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

CREATE OR REPLACE TEMP TABLE {sfDatabase}.ATO_CEG_STG.DELAER_SUMMARY_TEMP
AS
SELECT
    BDD.PERIOD_NAME AS PERIOD_NAME,
    BDD.PERIOD_START_DATE AS PERIOD_START_DATE,
    BDD.PERIOD_END_DATE AS PERIOD_END_DATE,
    BDD.PRODUCT_CODE AS PRODUCT_CODE,
    BDD.PRODUCT_DESC AS PRODUCT_DESC,
    BDD.TARIFF_CODE AS TARIFF_CODE,
    BDD.TARIFF_DESC AS TARIFF_DESC,
    BDD.PARTNER_CODE AS PARTNER_CODE,
    BDD.PARTNER_NAME AS PARTNER_NAME,
    CASE 
        WHEN TRIM(UPPER(BDD.COMMITMENT_TYPE)) IN ('NEW CONTRACT') THEN 'Connection'
        WHEN TRIM(UPPER(BDD.COMMITMENT_TYPE)) IN ('UPGRADE') THEN 'Upgrades'
    END AS CONNECTION_TYPE,
    BDD.COMMITMENT_TYPE AS COMMITMENT_TYPE,
    SUM(
        CASE
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) NOT LIKE 'CT%ADDON%' AND
                (TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%TARIFF%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%MRCSHARE%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%SUBSIDY%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%RECURRING%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%MONTHLY_RENEWAL%') THEN BDD.CREDIT_VAL
            ELSE 0
        END
    ) AS TARIFF_BONUS_TOTAL,
    SUM(
        CASE
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) NOT LIKE 'CT%ADDON%' AND
                (TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%TARIFF%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%MRCSHARE%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%SUBSIDY%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%RECURRING%' 
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%MONTHLY_RENEWAL%') THEN BDD.CREDIT_VAL
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS TARIFF_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%DEVICE%'
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%HANDSET%'
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_OMRC_RENEWAL_CONNECTION','CT_OMRC_RENEWAL_CONNECTION_BACK') THEN BDD.CREDIT_VAL
            ELSE 0
        END
    ) AS PROMOTION_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%DEVICE%'
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%HANDSET%'
                OR TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_OMRC_RENEWAL_CONNECTION','CT_OMRC_RENEWAL_CONNECTION_BACK') THEN BDD.CREDIT_VAL
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS PROMOTION_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%USIM%' THEN BDD.CREDIT_VAL
            ELSE 0
        END
    ) AS USIM_REFUND_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%USIM%' THEN BDD.CREDIT_VAL
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS USIM_REFUND_UNIT,
    SUM(BDD.CREDIT_VAL) AS SUBTOTAL_TOTAL,
    SUM(BDD.CREDIT_VAL) / COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS SUBTOTAL_UNIT,
    COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS QUANTITY,
    MAX('0') AS IS_POSTED,
    MAX('0') AS IS_FINALIZED,
    MAX(SYSDATE()) AS MODIFIED_DATE,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%ADDON%' THEN BDD.CREDIT_VAL
            ELSE 0
        END
    ) AS ADDON_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT%ADDON%' THEN BDD.CREDIT_VAL
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS ADDON_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_ADVANCE_BACK_ADJ','CT_ADVANCE_ADJ') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    ) AS ADVANCE_PAY_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_ADVANCE_BACK_ADJ','CT_ADVANCE_ADJ') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS ADVANCE_PAY_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_VOLUME_ADJ%' THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    ) AS VOLUME_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_VOLUME_ADJ%' THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS VOLUME_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_MANUAL%' OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_VOLUME_ADJ_BP%' THEN BDD.CREDIT_VAL
            ELSE 0 
        END
    ) AS MANUAL_ADJ_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_MANUAL%' OR TRIM(UPPER(BDD.CREDIT_TYPE)) LIKE 'CT_VOLUME_ADJ_BP%' THEN BDD.CREDIT_VAL
            ELSE 0 
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS MANUAL_ADJ_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_NONITU_TOPUP1') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    ) AS PAYG_TOPUP_BONUS_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_NONITU_TOPUP1') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS PAYG_TOPUP_BONUS_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_NONITU_REVSHARE') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    ) AS PAYG_REVSHARE_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_NONITU_REVSHARE') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS PAYG_REVSHARE_UNIT,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_ITU_REBATE', 'CT_PAYG_ITU_ENHANCED_REBATE','CT_PAYG_NONITU_REBATE') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    ) AS PAYG_REBATE_TOTAL,
    SUM(
        CASE 
            WHEN TRIM(UPPER(BDD.CREDIT_TYPE)) IN ('CT_PAYG_ITU_REBATE', 'CT_PAYG_ITU_ENHANCED_REBATE','CT_PAYG_NONITU_REBATE') THEN BDD.CREDIT_VAL 
            ELSE 0
        END
    )/COUNT(DISTINCT ORDER_ID, LINE_NUMBER, SUBLINE_NUMBER, EVENT_TYPE, PERIOD_NAME) AS PAYG_REBATE_UNIT,
    BDD.BUS_SERVICE_TYPE AS BUS_SERVICE_TYPE
FROM {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_DETAILS BDD
WHERE TRIM(UPPER(BDD.SOURCE)) NOT IN ('LEGACY')
  --AND BDD.PERIOD_NAME = TRIM(TO_CHAR(DATEADD(MONTH, -1, CURRENT_DATE()), 'MMMM YYYY')) || ' M'
  AND BDD.PERIOD_NAME = '{period_name_value}'
GROUP BY PERIOD_NAME, PERIOD_START_DATE, PERIOD_END_DATE, PRODUCT_CODE,
PRODUCT_DESC, TARIFF_CODE, TARIFF_DESC, PARTNER_CODE, PARTNER_NAME, COMMITMENT_TYPE, BUS_SERVICE_TYPE
ORDER BY PRODUCT_DESC, TARIFF_CODE;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)

# COMMAND ----------

query = f"""

INSERT INTO {sfDatabase}.PRS_CEG_EXT.B2C_DEALER_SUMMARY
(
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    PRODUCT_CODE,
    PRODUCT_DESC,
    TARIFF_CODE,
    TARIFF_DESC,
    PARTNER_CODE,
    PARTNER_NAME,
    CONNECTION_TYPE,
    COMMITMENT_TYPE,
    TARIFF_BONUS_TOTAL,
    TARIFF_BONUS_UNIT,
    PROMOTION_BONUS_TOTAL,
    PROMOTION_BONUS_UNIT,
    USIM_REFUND_TOTAL,
    USIM_REFUND_UNIT,
    SUBTOTAL_TOTAL,
    SUBTOTAL_UNIT,
    QUANTITY,
    IS_POSTED,
    IS_FINALIZED,
    MODIFIED_DATE,
    ADDON_BONUS_TOTAL,
    ADDON_BONUS_UNIT,
    ADVANCE_PAY_BONUS_TOTAL,
    ADVANCE_PAY_BONUS_UNIT,
    VOLUME_BONUS_TOTAL,
    VOLUME_BONUS_UNIT,
    MANUAL_ADJ_BONUS_TOTAL,
    MANUAL_ADJ_UNIT,
    PAYG_TOPUP_BONUS_TOTAL,
    PAYG_TOPUP_BONUS_UNIT,
    PAYG_REVSHARE_TOTAL,
    PAYG_REVSHARE_UNIT,
    PAYG_REBATE_TOTAL,
    PAYG_REBATE_UNIT,
    BUS_SERVICE_TYPE,
    INSERT_TS,
    UPDATE_TS
)
SELECT 
    PERIOD_NAME,
    PERIOD_START_DATE,
    PERIOD_END_DATE,
    PRODUCT_CODE,
    PRODUCT_DESC,
    TARIFF_CODE,
    TARIFF_DESC,
    PARTNER_CODE,
    PARTNER_NAME,
    CONNECTION_TYPE,
    COMMITMENT_TYPE,
    TARIFF_BONUS_TOTAL,
    TARIFF_BONUS_UNIT,
    PROMOTION_BONUS_TOTAL,
    PROMOTION_BONUS_UNIT,
    USIM_REFUND_TOTAL,
    USIM_REFUND_UNIT,
    SUBTOTAL_TOTAL,
    SUBTOTAL_UNIT,
    QUANTITY,
    IS_POSTED,
    IS_FINALIZED,
    MODIFIED_DATE,
    ADDON_BONUS_TOTAL,
    ADDON_BONUS_UNIT,
    ADVANCE_PAY_BONUS_TOTAL,
    ADVANCE_PAY_BONUS_UNIT,
    VOLUME_BONUS_TOTAL,
    VOLUME_BONUS_UNIT,
    MANUAL_ADJ_BONUS_TOTAL,
    MANUAL_ADJ_UNIT,
    PAYG_TOPUP_BONUS_TOTAL,
    PAYG_TOPUP_BONUS_UNIT,
    PAYG_REVSHARE_TOTAL,
    PAYG_REVSHARE_UNIT,
    PAYG_REBATE_TOTAL,
    PAYG_REBATE_UNIT,
    BUS_SERVICE_TYPE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM {sfDatabase}.ATO_CEG_STG.DELAER_SUMMARY_TEMP;

"""

#queryobject = sfUtils1.runQuery(options1, query)
cs.execute(query)